/* Generated by gg/tools/gg_convert.py - do not edit. */
#ifndef GG_DATA_H
#define GG_DATA_H

#include <stdint.h>

#define GG_BG_TILE_COUNT 68
#define GG_SPR_TILE_COUNT 24
#define GG_LEVEL_WIDTH 842

extern const uint8_t gg_bg_tiles[GG_BG_TILE_COUNT * 32];
extern const uint8_t gg_spr_tiles[GG_SPR_TILE_COUNT * 32];
extern const uint8_t gg_mt[256][4];
extern const uint8_t gg_ground_top[8];
extern const uint8_t gg_ground_bot[8];
extern const uint16_t gg_bg_palette[16];
extern const uint16_t gg_spr_palette[16];
extern const uint8_t gg_cube_frames[25][2];
extern const uint8_t famidash_metatile_collision[256];
extern const uint8_t dryout_map[GG_LEVEL_WIDTH * 16];

#endif
