/* Generated by gg/tools/gg_convert.py - do not edit. */
#ifndef GG_DATA_H
#define GG_DATA_H

#include <stdint.h>

#define GG_BG_TILE_COUNT 68
#define GG_SPR_TILE_COUNT 172
#define GG_LEVEL_WIDTH 842
#define GG_OBJ_COUNT 64

typedef struct { int8_t dx, dy; uint8_t tile; } GgSprItem;
typedef struct { uint8_t start, count; } GgObjDef;
typedef struct { uint16_t x; uint8_t y, type; } GgObj;

extern const uint8_t gg_bg_tiles[GG_BG_TILE_COUNT * 32];
extern const uint8_t gg_spr_tiles[GG_SPR_TILE_COUNT * 32];
extern const uint8_t gg_mt[256][4];
extern const uint8_t gg_ground_top[8];
extern const uint8_t gg_ground_bot[8];
extern const uint16_t gg_bg_palette[16];
extern const uint16_t gg_spr_palette[16];
/* [gravity_flipped * 25 + anim_frame][left/right] */
extern const uint8_t gg_cube_frames[50][2];
/* [gravity_flipped][tail/nose] */
extern const uint8_t gg_ship_tiles[2][2];
extern const GgSprItem gg_spr_items[70];
extern const GgObjDef gg_obj_defs[64];
extern const GgObj gg_objs[GG_OBJ_COUNT];
extern const uint16_t gg_sky_tab[64][2];   /* colour, darker */
extern const uint16_t gg_gnd_tab[64][4];   /* colour, darker, grid 18, grid 9 */
extern const uint8_t famidash_metatile_collision[256];
extern const uint8_t dryout_map[GG_LEVEL_WIDTH * 16];

#endif
