/* Generated by gg/tools/gg_music.py - do not edit. */
#ifndef GG_MUSIC_H
#define GG_MUSIC_H

#include <stdint.h>

#define GG_MUSIC_FIRST_BANK 4
#define GG_MUSIC_BANKS 1

extern const uint8_t * const gg_music_banks[GG_MUSIC_BANKS];

void music_start(void);
void music_stop(void);
void music_tick(void);

#endif
