#pragma bank 24
// Generated by tools/build_icon_select_gfx.py. Do not edit.

#include "icon_catalog.h"

BANKREF(icon_catalog)

const palette_color_t icon_palette_colors[NUM_PALETTE_COLORS] = {
    RGB8(125, 255,   0), // 0: Lime
    RGB8(  0, 255, 255), // 1: Cyan
    RGB8(255, 230,   0), // 2: Yellow
    RGB8(255, 120,   0), // 3: Orange
    RGB8(255,  30,  30), // 4: Red
    RGB8(255,   0, 200), // 5: Pink
    RGB8(160,  30, 255), // 6: Purple
    RGB8(  0, 110, 255), // 7: Blue
    RGB8(  0, 200,   0), // 8: Green
    RGB8(255, 255, 255), // 9: White
    RGB8(160, 160, 160), // 10: Grey
    RGB8( 90,  90,  90), // 11: Dark Grey
};

const uint8_t icon_dmg_shades[NUM_PALETTE_COLORS] = { 1, 1, 0, 1, 2, 1, 2, 2, 2, 0, 1, 3 };

palette_color_t icon_color(uint8_t idx) BANKED {
    return icon_palette_colors[idx < NUM_PALETTE_COLORS ? idx : 0];
}
