#pragma bank 14

#include <gb/gb.h>
#include <stdint.h>
#include <string.h>
#include "collision.h"
#include "famidash_metatiles.h"
#include "bg_parallax.h"
#include <gbdk/incbin.h>

// Level background tiles: every level loads the base sheet (load_bkg_tileset), then its
// own extra tiles, moves and metatile overrides from the lists generated by
// tools/build_bg_tiles.py out of levels/chr_data/bg_tiles.png (bg_level_tables.h).
#include "bg_level_tables.h"
INCBIN(bg_extra_tiles, "levels/chr_data/bg_extra_tiles.bin")   // per tile: normal + mirrored
INCBIN_EXTERN(bg_extra_tiles)
extern const uint8_t saw_anim_tiles[];   // saw_anim_data.c: SAW_ANIM_FRAMES x SAW_ANIM_TILES x 16 bytes
BANKREF_EXTERN(saw_anim)
static uint8_t mt_saws;
static uint8_t mt_big_saws;   // the level has big saws: SAW_CENTER_MT is their centre

// Metatile tables the renderer uses: the ROM tables, or a per-level copy in WRAM when
// the level moves sheet tiles or overrides metatile tiles.
static const uint8_t (*mt_tab)[4] = metatiles;
static const uint8_t (*mt_tab_rev)[4] = metatiles_rev;
static uint8_t mt_ram[2][FAMIDASH_NUM_METATILES][4];
static uint8_t mt_xlat[256];
static uint8_t mt_ram_level = 0xFF;   // level mt_ram was built for (it depends on the level only)

// ---- Saw animation: the saw tiles are rewritten through 3 frames (rotated anticlockwise).
// CGB: the VBlank handler GDMAs SAW_CHUNK_TILES tiles of the next frame per VBlank (the saw
// tiles are at VRAM bank 1 slots SAW_VRAM_BASE.. in every level). DMG: the VBlank handler copies
// DMG_SAW_TILES_PER_FRAME tiles per VBlank from bg_extra_tiles into the slots this level loaded
// them to (copying them from the main thread with set_bkg_data cost up to 40% of a frame).
#define SAW_STEP_FRAMES        2    // idle frames between finishing one animation frame and starting the next
#define SAW_CHUNK_TILES        13   // CGB tiles per VBlank (SAW_ANIM_TILES / 4)
#define DMG_SAW_TILES_PER_FRAME BG_SAW_DMG_MAX
uint8_t saw_on;                      // this level has saws (player.c: saw collision)
static uint8_t saw_reversed;
static uint8_t saw_frame;            // frame being / last uploaded
static uint8_t saw_pos;              // next tile of that frame; == SAW_ANIM_TILES: idle
static uint8_t saw_timer;
static uint8_t saw_issued;           // CGB: chunk handed to the VBlank handler, not yet done
static uint8_t *saw_dmg_dst[SAW_ANIM_TILES];   // DMG: VRAM address of each saw tile (0: not loaded)

static void saw_anim_reset(void) {
    saw_frame = 0;
    saw_pos = SAW_ANIM_TILES;
    saw_timer = 0;
    saw_issued = 0;
    bg_saw_pending = 0;
    bg_saw_dmg_n = 0;
}

// Call once per frame before waiting for VBlank (like request_bg_parallax)
void saw_anim_request(void) BANKED {
    if (!saw_on) return;
    uint8_t cgb = bg_gdma_isr_on;
    if (saw_issued) {
        if (cgb ? bg_saw_pending : bg_saw_dmg_n) return;
        saw_issued = 0;
        saw_pos += cgb ? SAW_CHUNK_TILES : DMG_SAW_TILES_PER_FRAME;
    }
    if (saw_pos >= SAW_ANIM_TILES) {
        if (++saw_timer < SAW_STEP_FRAMES) return;
        saw_timer = 0;
        saw_frame = (uint8_t)((saw_frame + 1) % SAW_ANIM_FRAMES);
        saw_pos = 0;
    }
    if (cgb) {
        bg_saw_bank = BANK(saw_anim);
        bg_saw_src = saw_anim_tiles + ((uint16_t)(saw_frame * SAW_ANIM_TILES + saw_pos) << 4);
        bg_saw_dst = (uint16_t)0x1000 + ((uint16_t)(SAW_VRAM_BASE + saw_pos) << 4);
        bg_saw_blocks = SAW_CHUNK_TILES;
        bg_saw_pending = 1;
    } else {
        // bg_extra_tiles is in this file's bank: per tile normal + mirrored (32 bytes)
        uint8_t n = (uint8_t)(SAW_ANIM_TILES - saw_pos);
        if (n > DMG_SAW_TILES_PER_FRAME) n = DMG_SAW_TILES_PER_FRAME;
        bg_saw_src = bg_extra_tiles + ((uint16_t)(saw_frame_first[saw_frame] + saw_pos) << 5) + (saw_reversed ? 16 : 0);
        bg_saw_dmg_dsts = saw_dmg_dst + saw_pos;
        bg_saw_bank = _current_bank;
        bg_saw_dmg_n = n;
    }
    saw_issued = 1;
}

// Display off: `count` tiles from sc_src (every other 16 bytes: bg_extra_tiles holds normal +
// mirrored) to consecutive tile slots at sc_dst.
static const uint8_t *sc_src;
static uint8_t *sc_dst;
static uint8_t sc_count;
static void copy_tiles_strided(void) __naked {
    __asm
        ld      hl, #_sc_dst
        ld      a, (hl+)
        ld      e, a
        ld      d, (hl)                 ; de = VRAM
        ld      hl, #_sc_src
        ld      a, (hl+)
        ld      h, (hl)
        ld      l, a                    ; hl = source
        ld      a, (_sc_count)
        ld      b, a
    1$:
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        inc     de
        ld      a, l
        add     a, #16                  ; skip the other orientation
        ld      l, a
        jr      NC, 2$
        inc     h
    2$:
        dec     b
        jr      NZ, 1$
        ret
    __endasm;
}

// CGB mirror mode by attribute: the tiles stay the normal sheet and the metatile tiles get the
// X flip attribute (tools/build_bg_tiles.py: the mirrored sheet / extra tiles are exactly the
// normal ones flipped). Off on DMG, and for a level with bank 0 tiles that are never mirrored
// (they would show flipped): those load the mirrored sheet like DMG.
uint8_t mt_cgb_flip;
void bg_level_set_flip_mode(uint8_t level) BANKED {
    mt_cgb_flip = 0;
    if (_cpu != CGB_TYPE) return;
    if (level < BG_LEVEL_COUNT) {
        const uint8_t *r = bg_level_cgb[level];
        for (uint8_t n = *r++; n; n--, r += 4) {
            if ((r[0] & 0x80) && !(r[0] & 1)) return;
        }
    }
    mt_cgb_flip = 1;
}

// VRAM address of BG tile slot (BG tiles 0..127 are at 0x9000, 128..255 at 0x8800)
#define BG_TILE_ADDR(slot) ((uint8_t *)((((slot) < 128u) ? 0x9000u : 0x8000u) + ((uint16_t)(slot) << 4)))

// Called after the base sheet was uploaded (display off). level: game_levels index.
void apply_level_bg_tiles(uint8_t level, uint8_t reversed) BANKED {
    const uint8_t *r;
    const uint8_t *ov;
    uint8_t n, n_moves, n_over, buf[16];
    uint8_t cgb = (_cpu == CGB_TYPE);
    uint8_t display_off = !(LCDC_REG & LCDCF_ON);
    mt_saws = cgb;
    mt_big_saws = 0;
    saw_on = 0;
    saw_anim_reset();
    mt_tab = metatiles;
    mt_tab_rev = metatiles_rev;
    if (level >= BG_LEVEL_COUNT) return;
    r = cgb ? bg_level_cgb[level] : bg_level_dmg[level];
    mt_big_saws = bg_level_big_saws[level];
    saw_on = bg_level_saws[level];
    saw_reversed = reversed;
    for (n = 0; n < SAW_ANIM_TILES; n++) saw_dmg_dst[n] = 0;

    // Extra tiles: (VRAM bank, slot, count, first extra tile); bank bit 7 = never mirrored
    for (n = *r++; n; n--) {
        uint8_t bank = *r++, dst = *r++, count = *r++;
        uint8_t first_tile = *r++;
        const uint8_t *src = bg_extra_tiles + (uint16_t)first_tile * 32u;
        if (!cgb && count == 1 && first_tile >= saw_frame_first[0] && first_tile < saw_frame_first[0] + SAW_ANIM_TILES) {
            // BG tiles 0..127 are at 0x9000, 128..255 at 0x8800
            saw_dmg_dst[first_tile - saw_frame_first[0]] = (uint8_t *)((dst < 128u ? 0x9000u : 0x8000u) + ((uint16_t)dst << 4));
        }
        if (reversed && !(bank & 0x80) && !mt_cgb_flip) src += 16;
        if (cgb) VBK_REG = bank & 1;
        if (display_off) {
            if (dst < 128u && (uint8_t)(dst + count) > 128u) {
                // the run crosses from 0x9000.. to 0x8800..
                uint8_t first = (uint8_t)(128u - dst);
                sc_src = src; sc_dst = BG_TILE_ADDR(dst); sc_count = first;
                copy_tiles_strided();
                src += (uint16_t)first << 5;
                dst = 128u; count -= first;
            }
            if (count) {
                sc_src = src; sc_dst = BG_TILE_ADDR(dst); sc_count = count;
                copy_tiles_strided();
            }
            count = 0;
        } else {
            while (count--) {
                set_bkg_data(dst++, 1, src);
                src += 32;
            }
        }
        if (cgb) VBK_REG = VBK_TILES;
    }
    // CGB: the saws just loaded from bg_extra_tiles are the DMG version (outlined); stream
    // frame 0 of the CGB art (saw_anim_tiles) right away
    if (cgb && saw_on) saw_pos = 0;
    n_moves = *r;
    ov = r + 1 + (n_moves << 1);
    n_over = *ov++;
    if (!n_moves && !n_over) return;

    // Moved sheet tiles (DMG: out of the coin sprite tiles) -> per-level metatile table. The
    // table only depends on the level, so a mirror portal or a respawn only moves the tiles again.
    uint8_t rebuild = (mt_ram_level != level);
    if (rebuild) {
        n = 0;
        do { mt_xlat[n] = n; } while (++n);
    }
    for (n = n_moves, r++; n; n--) {
        uint8_t dst = *r++, src = *r++;
        if (display_off) {
            memcpy(BG_TILE_ADDR(dst), BG_TILE_ADDR(src), 16);
        } else {
            get_bkg_data(src, 1, buf);
            set_bkg_data(dst, 1, buf);
        }
        mt_xlat[src] = dst;
    }
    mt_tab = mt_ram[0];
    mt_tab_rev = mt_ram[1];
    if (!rebuild) return;
    mt_ram_level = level;
    {
        const uint8_t *s = &metatiles[0][0];
        uint8_t *d = &mt_ram[0][0][0];
        for (uint16_t j = 0; j < FAMIDASH_NUM_METATILES * 4u; j++) d[j] = mt_xlat[s[j]];
    }
    for (n = n_over; n; n--) {
        uint8_t m = *ov++, q = *ov++;
        mt_ram[0][m][q] = *ov++;
    }
    n = 0;
    do {
        // reversed table = each metatile's tiles swapped left/right (mirrored sheet)
        mt_ram[1][n][0] = mt_ram[0][n][1]; mt_ram[1][n][1] = mt_ram[0][n][0];
        mt_ram[1][n][2] = mt_ram[0][n][3]; mt_ram[1][n][3] = mt_ram[0][n][2];
    } while (++n);
}

// Saw metatile: writes its 4 tiles/attributes (bank 1, mirrored when reversed).
// Positions whose Famidash tile is empty keep the normal transparent tile.
static uint8_t *saw_dst;
static uint8_t *saw_dst_attr;
static void put_saw(uint8_t si, uint8_t reversed, uint8_t r0, uint8_t r1, uint8_t tl_x, uint8_t tr_x) {
    const uint8_t *st = saw_mt_tiles[si - 1];
    uint8_t order0 = reversed ? 1 : 0;
    for (uint8_t i = 0; i < 4; i++) {
        uint8_t t = st[(uint8_t)(i ^ order0)];
        if (t == 0xFF) {
            *saw_dst++ = ((i < 2) ? r0 : r1) + ((i & 1) ? tr_x : tl_x);
            *saw_dst_attr++ = 0x0B;
        } else {
            *saw_dst++ = t;
            *saw_dst_attr++ = reversed ? 0x28 : 0x08; // bank 1, palette 0 (+ X flip)
        }
    }
}

#define BKG_MT_H 16

// Vertical streaming: the VRAM ring's 16 metatile rows hold map rows mt_band .. mt_band+15, map
// row m in VRAM metatile row m & 15 (so SCY = camera y & 255). gameplay.c moves the band with the
// camera one row at a time; the row entering the band is written by the row job below. On CGB
// the band can reach GROUND_ROW, the row below the map, which shows the ground strip.
uint8_t mt_band;
static const uint8_t ground_top[8] = { 48, 49, 49, 49, 49, 49, 49, 50 };
static const uint8_t ground_bot[8] = { 51, 52, 52, 52, 52, 52, 52, 53 };
// CGB parallax tile row of map row m: (m % 3) * 16 (rows of the parallax pattern repeat every 3)
static const uint8_t row_ty0[48] = {
    0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0,
    16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16,
    32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32
};
#define BAND_ROW(k) ((uint8_t)(mt_band + ((uint8_t)((k) - mt_band) & 15u)))

static uint8_t metatile_column_buf[BKG_MT_H * 8];   // tiles, then (+BKG_MT_H * 4) attributes
#define metatile_column_tiles       (metatile_column_buf)
#define metatile_column_attributes  (metatile_column_buf + BKG_MT_H * 4)
static uint8_t col_buf[16];

static uint16_t cur_map_col;

// Builds VRAM metatile rows [r_start, r_end) of the column in col_buf into
// metatile_column_tiles/attributes.
//
// CGB: hand-written loop for the common metatile (tiles from the table, the empty tile 12
// becomes the parallax tile of the row/slot, attribute = metatile palette or 0x0B for the
// parallax), then C fixes up the ground row and the saw metatiles. DMG: 4 table bytes per row.
static const uint8_t *bm_src;       // metatile ids of the first row
static uint8_t *bm_dst;             // tiles of the first row (attributes: +BKG_MT_H * 4)
static const uint8_t *bm_tab;       // metatile table (4 tile ids per metatile)
static const uint8_t *bm_r0p;       // row_r0 of the first row
static uint8_t bm_n;                // rows
static uint8_t bm_pal, bm_r0cur;
static uint8_t bm_off[4];           // parallax tile = row base + bm_off[tile of the metatile]
static uint8_t bm_info[256];        // per metatile: palette | 0x80 if it is drawn as a saw (C fix-up)
static uint8_t bm_info_key = 0xFF;  // (mt_saws, mt_big_saws) bm_info was built for
static uint8_t bm_saw;              // the asm saw a saw metatile
static uint8_t bm_flip;             // 0x20 (X flip) in CGB flip mirror mode, else 0
static uint8_t row_r0[16];          // first parallax tile of each VRAM metatile row (for mt_band)
static uint8_t row_r0_band = 0xFF;

static void build_rows_cgb_asm(void) __naked {
    __asm
        ld      hl, #_bm_dst
        ld      a, (hl+)
        ld      e, a
        ld      d, (hl)                 ; de = tiles
        ld      a, e
        add     a, #64
        ld      c, a
        ld      a, d
        adc     a, #0
        ld      b, a                    ; bc = attributes (tiles + 64)
    1$:
        ; row start: id = *bm_src++, r0 = *bm_r0p++
        ld      hl, #_bm_src
        ld      a, (hl+)
        ld      h, (hl)
        ld      l, a
        ld      a, (hl+)                ; a = metatile id
        push    af
        ld      a, l
        ld      (_bm_src), a
        ld      a, h
        ld      (_bm_src + 1), a
        ld      hl, #_bm_r0p
        ld      a, (hl+)
        ld      h, (hl)
        ld      l, a
        ld      a, (hl+)
        ld      (_bm_r0cur), a
        ld      a, l
        ld      (_bm_r0p), a
        ld      a, h
        ld      (_bm_r0p + 1), a
        pop     af                      ; a = id
        push    af
        ld      hl, #_bm_info
        add     a, l
        ld      l, a
        jr      NC, 2$
        inc     h
    2$:
        ld      a, (hl)
        bit     7, a
        jr      Z, 5$
        and     a, #0x7F
        ld      hl, #_bm_saw
        ld      (hl), #1
    5$:
        ld      hl, #_bm_flip
        or      a, (hl)
        ld      (_bm_pal), a
        pop     af
        ld      l, a
        ld      h, #0
        add     hl, hl
        add     hl, hl
        ld      a, (_bm_tab)
        add     a, l
        ld      l, a
        ld      a, (_bm_tab + 1)
        adc     a, h
        ld      h, a                    ; hl = the 4 tiles of the metatile
        ld      a, (hl+)
        cp      a, #12
        jr      NZ, 30$
        push    hl
        ld      hl, #(_bm_off + 0)
        ld      a, (_bm_r0cur)
        add     a, (hl)
        pop     hl
        ld      (de), a
        inc     de
        ld      a, #0x0B
        jr      40$
    30$:
        ld      (de), a
        inc     de
        ld      a, (_bm_pal)
    40$:
        ld      (bc), a
        inc     bc
        ld      a, (hl+)
        cp      a, #12
        jr      NZ, 31$
        push    hl
        ld      hl, #(_bm_off + 1)
        ld      a, (_bm_r0cur)
        add     a, (hl)
        pop     hl
        ld      (de), a
        inc     de
        ld      a, #0x0B
        jr      41$
    31$:
        ld      (de), a
        inc     de
        ld      a, (_bm_pal)
    41$:
        ld      (bc), a
        inc     bc
        ld      a, (hl+)
        cp      a, #12
        jr      NZ, 32$
        push    hl
        ld      hl, #(_bm_off + 2)
        ld      a, (_bm_r0cur)
        add     a, (hl)
        pop     hl
        ld      (de), a
        inc     de
        ld      a, #0x0B
        jr      42$
    32$:
        ld      (de), a
        inc     de
        ld      a, (_bm_pal)
    42$:
        ld      (bc), a
        inc     bc
        ld      a, (hl+)
        cp      a, #12
        jr      NZ, 33$
        push    hl
        ld      hl, #(_bm_off + 3)
        ld      a, (_bm_r0cur)
        add     a, (hl)
        pop     hl
        ld      (de), a
        inc     de
        ld      a, #0x0B
        jr      43$
    33$:
        ld      (de), a
        inc     de
        ld      a, (_bm_pal)
    43$:
        ld      (bc), a
        inc     bc
        ld      a, (_bm_n)
        dec     a
        ld      (_bm_n), a
        jp      NZ, 1$
        ret
    __endasm;
}

static void build_rows_dmg_asm(void) __naked {
    __asm
        ld      hl, #_bm_src
        ld      a, (hl+)
        ld      c, a
        ld      b, (hl)                 ; bc = metatile ids
        ld      hl, #_bm_dst
        ld      a, (hl+)
        ld      e, a
        ld      d, (hl)                 ; de = tiles
    1$:
        ld      a, (bc)
        inc     bc
        ld      l, a
        ld      h, #0
        add     hl, hl
        add     hl, hl
        ld      a, (_bm_tab)
        add     a, l
        ld      l, a
        ld      a, (_bm_tab + 1)
        adc     a, h
        ld      h, a
        ld      a, (hl+)
        ld      (de), a
        inc     de
        ld      a, (hl+)
        ld      (de), a
        inc     de
        ld      a, (hl+)
        ld      (de), a
        inc     de
        ld      a, (hl)
        ld      (de), a
        inc     de
        ld      a, (_bm_n)
        dec     a
        ld      (_bm_n), a
        jr      NZ, 1$
        ret
    __endasm;
}

// ids: the column's 16 metatile ids (VRAM rows), out: 64 tile bytes then 64 attribute bytes
static void build_mt_rows(uint16_t map_col, const uint8_t *ids, uint8_t *out, uint8_t reversed, uint8_t r_start, uint8_t r_end) {
    bm_src = ids + r_start;
    bm_dst = out + ((uint8_t)r_start << 2);
    bm_tab = reversed ? &mt_tab_rev[0][0] : &mt_tab[0][0];
    bm_n = (uint8_t)(r_end - r_start);
    if (_cpu != CGB_TYPE) {
        build_rows_dmg_asm();
        return;
    }

    uint8_t vram_slot = (uint8_t)(map_col & 15u);
    if (reversed) vram_slot = (uint8_t)(-(int8_t)vram_slot & 15u);
    uint8_t tl_x = (uint8_t)((vram_slot & 3u) << 1);
    uint8_t tr_x = tl_x + 1u;
    bm_flip = (reversed && mt_cgb_flip) ? 0x20 : 0;
    bm_off[0] = tl_x; bm_off[1] = tr_x;
    bm_off[2] = (uint8_t)(tl_x + 8u); bm_off[3] = (uint8_t)(tr_x + 8u);

    if (row_r0_band != mt_band) {
        for (uint8_t r = 0; r < 16; r++) row_r0[r] = row_ty0[BAND_ROW(r)];
        row_r0_band = mt_band;
    }
    bm_r0p = row_r0 + r_start;
    uint8_t key = (uint8_t)((mt_saws << 1) | mt_big_saws);
    if (key != bm_info_key) {
        uint8_t n = 0;
        do {
            uint8_t info = famidash_metatile_palettes[n];
            if (saw_mt_index[n] && mt_saws && (n != SAW_CENTER_MT || mt_big_saws)) info |= 0x80;
            bm_info[n] = info;
        } while (++n);
        bm_info_key = key;
    }
    bm_saw = 0;
    build_rows_cgb_asm();

    // The ground row (below the map) shows the ground strip
    uint8_t gr = (uint8_t)(GROUND_ROW & 15u);
    uint8_t has_ground = ((uint8_t)(GROUND_ROW - mt_band) <= 15u && gr >= r_start && gr < r_end);
    if (has_ground) {
        uint8_t *d = out + (gr << 2);
        uint8_t *da = out + BKG_MT_H * 4 + (gr << 2);
        d[0] = ground_top[tl_x]; d[1] = ground_top[tr_x];
        d[2] = ground_bot[tl_x]; d[3] = ground_bot[tr_x];
        da[0] = da[1] = da[2] = da[3] = 0x0C;   // Bank 1 + Palette 4
    }
    // Saw metatiles: bank 1 tiles (mirrored when reversed)
    if (!bm_saw) return;
    for (uint8_t r = r_start; r < r_end; r++) {
        uint8_t metatile_id = ids[r];
        uint8_t si = saw_mt_index[metatile_id];
        if (si && mt_saws && (metatile_id != SAW_CENTER_MT || mt_big_saws) && !(has_ground && r == gr)) {
            uint8_t r0 = row_r0[r];
            saw_dst = out + (r << 2);
            saw_dst_attr = out + BKG_MT_H * 4 + (r << 2);
            put_saw(si, reversed, r0, (uint8_t)(r0 + 8u), tl_x, tr_x);
        }
    }
}

void prepare_mt_column(uint16_t map_col, const uint8_t* map, uint8_t map_bank, uint8_t reversed) BANKED {
    cur_map_col = map_col;
    get_map_column(map_col, map, map_bank, col_buf, mt_band);
    build_mt_rows(map_col, col_buf, metatile_column_buf, reversed, 0, BKG_MT_H);
}

// Sliced version: step 0..3 builds metatile rows 4*step .. 4*step+3
// (step 0 also fetches the map column). See flush_mt_column_slice().
#ifdef DEBUG_PROFILE
extern volatile uint8_t gpmark;
#define PROF_MARK(n) (gpmark = (n))
#else
#define PROF_MARK(n)
#endif
void prepare_mt_column_slice(uint16_t map_col, const uint8_t* map, uint8_t map_bank, uint8_t reversed, uint8_t step) BANKED {
    PROF_MARK(11);
    if (step == 0) {
        cur_map_col = map_col;
        get_map_column(map_col, map, map_bank, col_buf, mt_band);
    }
    PROF_MARK(12);
#ifdef DEBUG_PROFILE_NOINT
    disable_interrupts();
#endif
    build_mt_rows(cur_map_col, col_buf, metatile_column_buf, reversed, (uint8_t)(step << 2), (uint8_t)((step << 2) + 4u));
#ifdef DEBUG_PROFILE_NOINT
    enable_interrupts();
#endif
    PROF_MARK(13);
}

// The band moved while a sliced column was being built: re-read its map column for the new
// band, or the slices still to come would write the row that left the band over the one the
// row job just streamed in (a wrong metatile, and on CGB a wrong palette, until the ring
// column is rebuilt).
void refetch_mt_column(const uint8_t* map, uint8_t map_bank) BANKED {
    get_map_column(cur_map_col, map, map_bank, col_buf, mt_band);
}

// Display off: the 2 x 32 bytes at fc_src to the 2 map columns at fc_dst (32 rows, 32 bytes apart)
static const uint8_t *fc_src;
static uint8_t *fc_dst;
static void flush_col_plain(void) __naked {
    __asm
        ld      hl, #_fc_dst
        ld      a, (hl+)
        ld      e, a
        ld      d, (hl)                 ; de = map address
        ld      hl, #_fc_src
        ld      a, (hl+)
        ld      h, (hl)
        ld      l, a                    ; hl = source
        ld      b, #32
    1$:
        ld      a, (hl+)
        ld      (de), a
        inc     e
        ld      a, (hl+)
        ld      (de), a
        ld      a, e
        add     a, #31
        ld      e, a
        jr      NC, 2$
        inc     d
    2$:
        dec     b
        jr      NZ, 1$
        ret
    __endasm;
}

void flush_mt_column(uint8_t ring_col) BANKED {
    uint8_t bx = ring_col << 1;
    if (!(LCDC_REG & LCDCF_ON)) {
        // display off (level start, respawn, mirror portal): plain writes, no STAT waits
        uint8_t *map = (LCDC_REG & LCDCF_BG9C00) ? (uint8_t *)0x9C00 : (uint8_t *)0x9800;
        fc_dst = map + bx;
        VBK_REG = VBK_TILES;
        fc_src = metatile_column_tiles;
        flush_col_plain();
        if (_cpu == CGB_TYPE) {
            VBK_REG = VBK_ATTRIBUTES;
            fc_dst = map + bx;
            fc_src = metatile_column_attributes;
            flush_col_plain();
            VBK_REG = VBK_TILES;
        }
        return;
    }
    VBK_REG = VBK_TILES;
    set_bkg_tiles(bx, 0, 2, BKG_MT_H << 1, metatile_column_tiles);
    if (_cpu == CGB_TYPE) {
        VBK_REG = VBK_ATTRIBUTES;
        set_bkg_tiles(bx, 0, 2, BKG_MT_H << 1, metatile_column_attributes);
        VBK_REG = VBK_TILES;
    }
}

// Writes tile rows 8*step .. 8*step+7 of the prepared column (see prepare_mt_column_slice).
void flush_mt_column_slice(uint8_t ring_col, uint8_t step) BANKED {
    uint8_t bx = ring_col << 1;
    uint8_t ty = (uint8_t)(step << 3);
    uint8_t off = (uint8_t)(ty << 1);
    VBK_REG = VBK_TILES;
    set_bkg_tiles(bx, ty, 2, 8, metatile_column_tiles + off);
    if (_cpu == CGB_TYPE) {
        VBK_REG = VBK_ATTRIBUTES;
        set_bkg_tiles(bx, ty, 2, 8, metatile_column_attributes + off);
        VBK_REG = VBK_TILES;
    }
}

// Same as flush_mt_column_slice() but the VBlank handler does the VRAM writes.
void request_mt_column_slice(uint8_t ring_col, uint8_t step) BANKED {
    uint8_t off = (uint8_t)(step << 4);
    bg_cj_x = (uint8_t)(ring_col << 1);
    bg_cj_y = (uint8_t)(step << 3);
    bg_cj_tiles = metatile_column_tiles + off;
    bg_cj_attrs = metatile_column_attributes + off;
    bg_cj_pending = 1;
}

void fill_scroll_bg(const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    uint16_t cols = (map_w < 16) ? map_w : 16;
    for (uint16_t c = 0; c < cols; c++) {
        prepare_mt_column(c, map, map_bank, reversed);
        flush_mt_column((uint8_t)(c % 16));
    }
}

// ---- Row job: writes map row `row` into its VRAM metatile row (row & 15) for ring positions
// first .. first+n-1, reading the level map for the CURRENT loaded_r. Because it always uses the
// current state it never overwrites a freshly streamed column with stale data.
static uint8_t row_tiles[2][16];   // top / bottom tile row of ROW_JOB_SLOTS ring positions
static uint8_t row_attrs[2][16];

// DMG: row_tiles from the metatile ids rt_ids[0 .. rt_n-1] through the table rt_mt
// (hand-written: in C it took ~0.8k dots per position)
static uint8_t rt_ids[16];
static uint8_t rt_n;
static const uint8_t *rt_mt;
static void row_tiles_dmg(void) __naked {
    __asm
        ld      de, #_rt_ids
        ld      bc, #_row_tiles         ; top tile row (the bottom one is 16 bytes on)
        ld      a, (_rt_n)
    1$:
        push    af
        ld      a, (de)
        inc     de
        push    de
        ld      l, a
        ld      h, #0
        add     hl, hl
        add     hl, hl
        ld      a, (_rt_mt)
        add     a, l
        ld      l, a
        ld      a, (_rt_mt + 1)
        adc     a, h
        ld      h, a                    ; hl = the 4 tiles of the metatile
        ld      e, c
        ld      d, b
        ld      a, (hl+)
        ld      (de), a
        inc     de
        ld      a, (hl+)
        ld      (de), a
        ld      a, e
        add     a, #15
        ld      e, a
        adc     a, d
        sub     a, e
        ld      d, a                    ; de = same position, bottom tile row
        ld      a, (hl+)
        ld      (de), a
        inc     de
        ld      a, (hl)
        ld      (de), a
        inc     bc
        inc     bc
        pop     de
        pop     af
        dec     a
        jr      NZ, 1$
        ret
    __endasm;
}

static void build_row_slots(uint8_t first, uint8_t n, uint8_t row, uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) {
    const uint8_t (*mt_table)[4] = reversed ? mt_tab_rev : mt_tab;
    uint8_t ids[BG_RJ_SLOTS];
    uint8_t *t0 = row_tiles[0];
    uint8_t *t1 = row_tiles[1];
    if (_cpu != CGB_TYPE) {
        // DMG: tiles straight from the metatile table (no attributes, parallax or saw tiles)
        get_map_row_slots(first, n, row, loaded_r, reversed, map, map_w, map_bank, rt_ids);
        rt_n = n;
        rt_mt = mt_table[0];
        row_tiles_dmg();
        return;
    }
    uint8_t *a0 = row_attrs[0];
    uint8_t *a1 = row_attrs[1];
    if (row == GROUND_ROW) {
        for (uint8_t i = 0; i < n; i++) {
            uint8_t s = first + i;
            *t0++ = ground_top[(s << 1) & 7u]; *t0++ = ground_top[((s << 1) + 1u) & 7u];
            *t1++ = ground_bot[(s << 1) & 7u]; *t1++ = ground_bot[((s << 1) + 1u) & 7u];
            *a0++ = 0x0C; *a0++ = 0x0C; *a1++ = 0x0C; *a1++ = 0x0C;
        }
        return;
    }
    get_map_row_slots(first, n, row, loaded_r, reversed, map, map_w, map_bank, ids);
    uint8_t r0 = row_ty0[row];
    uint8_t flip = (reversed && mt_cgb_flip) ? 0x20 : 0;
    for (uint8_t i = 0; i < n; i++) {
        uint8_t tiles[4];
        uint8_t attrs[4];
        uint8_t slot = first + i;
        if (reversed) slot = (uint8_t)(-(int8_t)slot & 15u);
        uint8_t tl_x = (uint8_t)((slot & 3u) << 1);
        uint8_t tr_x = tl_x + 1u;
        uint8_t mt_id = ids[i];
        const uint8_t *mt = mt_table[mt_id];
        uint8_t pal = famidash_metatile_palettes[mt_id];
        for (uint8_t q = 0; q < 4; q++) {
            uint8_t t = mt[q];
            if (t == 12) {
                tiles[q] = (q < 2 ? r0 : (uint8_t)(r0 + 8u)) + ((q & 1) ? tr_x : tl_x);
                attrs[q] = 0x0B;
            } else {
                tiles[q] = t;
                attrs[q] = (uint8_t)(pal | flip);
            }
        }
        uint8_t si = saw_mt_index[mt_id];
        if (si && mt_saws && (mt_id != SAW_CENTER_MT || mt_big_saws)) {
            saw_dst = tiles; saw_dst_attr = attrs;
            put_saw(si, reversed, r0, (uint8_t)(r0 + 8u), tl_x, tr_x);
        }
        *t0++ = tiles[0]; *t0++ = tiles[1]; *t1++ = tiles[2]; *t1++ = tiles[3];
        *a0++ = attrs[0]; *a0++ = attrs[1]; *a1++ = attrs[2]; *a1++ = attrs[3];
    }
}

// CGB: builds the slots into the VBlank handler's request buffer and requests the upload
void request_row_slots(uint8_t first, uint8_t row, uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    build_row_slots(first, BG_RJ_SLOTS, row, loaded_r, map, map_w, map_bank, reversed);
    memcpy(bg_rj_tiles, row_tiles, sizeof(row_tiles));
    if (_cpu == CGB_TYPE) memcpy(bg_rj_attrs, row_attrs, sizeof(row_attrs));
    bg_rj_x = (uint8_t)(first << 1);
    bg_rj_y = (uint8_t)((row & 15u) << 1);
    bg_rj_pending = 1;
}

// Main thread version (DMG, and CGB without the VBlank handler): call right after VBlank started
void flush_row_slots(uint8_t first, uint8_t count, uint8_t row, uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    build_row_slots(first, count, row, loaded_r, map, map_w, map_bank, reversed);
    uint8_t x = (uint8_t)(first << 1);
    uint8_t y = (uint8_t)((row & 15u) << 1);
    uint8_t w = (uint8_t)(count << 1);
    VBK_REG = VBK_TILES;
    set_bkg_tiles(x, y, w, 1, row_tiles[0]);
    set_bkg_tiles(x, (uint8_t)(y + 1u), w, 1, row_tiles[1]);
    if (_cpu == CGB_TYPE) {
        VBK_REG = VBK_ATTRIBUTES;
        set_bkg_tiles(x, y, w, 1, row_attrs[0]);
        set_bkg_tiles(x, (uint8_t)(y + 1u), w, 1, row_attrs[1]);
        VBK_REG = VBK_TILES;
    }
}

void flush_ground_row(void) BANKED {
    if (_cpu != CGB_TYPE || (uint8_t)(GROUND_ROW - mt_band) > 15u) return;
    uint8_t y = (uint8_t)((GROUND_ROW & 15u) << 1);
    VBK_REG = 0;
    for (uint8_t k = 0; k < 4; k++) {
        set_bkg_tiles((uint8_t)(k << 3), y, 8, 1, ground_top);
        set_bkg_tiles((uint8_t)(k << 3), (uint8_t)(y + 1u), 8, 1, ground_bot);
    }
    VBK_REG = 1;
    fill_bkg_rect(0, y, 32, 2, 0x0C);
    VBK_REG = 0;
}

// ---- CGB seamless mirror portal (gameplay.c): the mirrored picture is built in the BG map that
// is not shown, a column / map row at a time while the game runs, then LCDC switches maps. That
// map is not displayed, but VRAM is still locked while the PPU draws (mode 3), so the writes go
// in short bursts at the start of HBlank (>= 167 dots until the next mode 3: the rest of
// HBlank plus mode 2). Double speed only (CGB): a burst is <= ~130 dots.
static const uint8_t *mjw_src;
static uint8_t *mjw_dst;
static uint8_t mjw_n;
static uint8_t mj_col[16];
static uint8_t mj_out[BKG_MT_H * 8];

// Returns at the start of an HBlank with interrupts disabled (the caller enables them again).
// Interrupts stay enabled while waiting for mode 3.
static void hblank_sync(void) __naked {
    __asm
    1$:
        ei
        ldh     a, (_STAT_REG + 0)
        and     a, #3
        cp      a, #3
        jr      NZ, 1$                  ; wait for mode 3 (drawing)
        di
        ldh     a, (_STAT_REG + 0)
        and     a, #3
        cp      a, #3
        jr      NZ, 1$                  ; an interrupt ran in between: again
    2$:
        ldh     a, (_STAT_REG + 0)
        and     a, #3
        jr      NZ, 2$                  ; wait for mode 0 (HBlank)
        ret
    __endasm;
}

// 2 bytes x 32 rows from mjw_src (contiguous) to mjw_dst (rows 32 bytes apart), 4 rows a burst
static void mj_write_col_asm(void) __naked {
    __asm
        ld      a, #8
        ld      (_mjw_n), a
        ld      hl, #_mjw_src
        ld      a, (hl+)
        ld      e, a
        ld      d, (hl)                 ; de = source
        ld      hl, #_mjw_dst
        ld      a, (hl+)
        ld      h, (hl)
        ld      l, a                    ; hl = map
        ld      bc, #31
    1$:
        call    _hblank_sync
        .rept 4
        ld      a, (de)
        inc     de
        ld      (hl+), a
        ld      a, (de)
        inc     de
        ld      (hl), a
        add     hl, bc
        .endm
        ei
        ld      a, (_mjw_n)
        dec     a
        ld      (_mjw_n), a
        jr      NZ, 1$
        ret
    __endasm;
}

// mjw_n x 8 contiguous bytes from mjw_src to mjw_dst, 8 bytes a burst
static void mj_write_run_asm(void) __naked {
    __asm
        ld      hl, #_mjw_src
        ld      a, (hl+)
        ld      e, a
        ld      d, (hl)
        ld      hl, #_mjw_dst
        ld      a, (hl+)
        ld      h, (hl)
        ld      l, a
    1$:
        call    _hblank_sync
        .rept 8
        ld      a, (de)
        inc     de
        ld      (hl+), a
        .endm
        ei
        ld      a, (_mjw_n)
        dec     a
        ld      (_mjw_n), a
        jr      NZ, 1$
        ret
    __endasm;
}

// Map column map_col for `reversed` (current mt_band) into its ring slot of the BG map at
// map_hi << 8 (0x98 / 0x9C). CGB, display on.
void mj_build_column(uint16_t map_col, const uint8_t* map, uint8_t map_bank, uint8_t reversed, uint8_t map_hi) BANKED {
    uint8_t slot = (uint8_t)(map_col & 15u);
    if (reversed) slot = (uint8_t)(-(int8_t)slot & 15u);
    get_map_column(map_col, map, map_bank, mj_col, mt_band);
    build_mt_rows(map_col, mj_col, mj_out, reversed, 0, BKG_MT_H);
    uint8_t *dst = (uint8_t *)((uint16_t)map_hi << 8) + (uint8_t)(slot << 1);
    VBK_REG = 0;
    mjw_src = mj_out; mjw_dst = dst;
    mj_write_col_asm();
    VBK_REG = 1;
    mjw_src = mj_out + BKG_MT_H * 4; mjw_dst = dst;
    mj_write_col_asm();
    VBK_REG = 0;
}

// Map row `row` (all 16 ring positions, the columns loaded_r maps them to) into the BG map at
// map_hi << 8. CGB, display on.
void mj_build_row(uint8_t row, uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed, uint8_t map_hi) BANKED {
    uint8_t *base = (uint8_t *)((uint16_t)map_hi << 8) + ((uint16_t)(row & 15u) << 6);
    for (uint8_t half = 0; half < 2; half++) {
        build_row_slots((uint8_t)(half << 3), BG_RJ_SLOTS, row, loaded_r, map, map_w, map_bank, reversed);
        uint8_t *d = base + (uint8_t)(half << 4);
        for (uint8_t b = 0; b < 2; b++) {
            VBK_REG = b;
            mjw_src = b ? row_attrs[0] : row_tiles[0]; mjw_dst = d; mjw_n = 2;
            mj_write_run_asm();
            mjw_src = b ? row_attrs[1] : row_tiles[1]; mjw_dst = d + 32; mjw_n = 2;
            mj_write_run_asm();
        }
    }
    VBK_REG = 0;
}

// DMG mirror portal, display off: mirrors the 0x9800 map in place. On DMG a reversed column is
// the normal one with its left / right tiles swapped (same tile ids, the mirrored sheet) in ring
// slot (-col) & 15, so the whole map is its own mirror image: tile x goes to (1 - x) & 31.
static void reflect_map_asm(void) __naked {
    __asm
        ld      hl, #0x9800
        ld      b, #32
    1$:
        push    hl
        ld      a, (hl+)                ; swap x 0 and 1
        ld      c, (hl)
        ld      (hl-), a
        ld      (hl), c
        ld      d, h
        ld      a, l
        add     a, #2
        ld      e, a                    ; de = x 2 (rows are 32-byte aligned: no carry)
        ld      a, l
        add     a, #31
        ld      l, a                    ; hl = x 31
        .rept 15                        ; swap x 2..16 with 31..17
        ld      a, (de)
        ld      c, (hl)
        ld      (hl-), a
        ld      a, c
        ld      (de), a
        inc     e
        .endm
        pop     hl
        ld      de, #32
        add     hl, de
        dec     b
        jr      NZ, 1$
        ret
    __endasm;
}

void bg_map_reflect(void) BANKED {
    reflect_map_asm();
}
