#pragma bank 14

#include <gb/gb.h>
#include <stdint.h>
#include <string.h>
#include "collision.h"
#include "famidash_metatiles.h"
#include "bg_parallax.h"
#include <gbdk/incbin.h>

// Level background tiles: every level loads the base sheet (load_bkg_tileset), then its
// own extra tiles, moves and metatile overrides from the lists generated by
// tools/build_bg_tiles.py out of levels/chr_data/bg_tiles.png (bg_level_tables.h).
#include "bg_level_tables.h"
INCBIN(bg_extra_tiles, "levels/chr_data/bg_extra_tiles.bin")   // per tile: normal + mirrored
INCBIN_EXTERN(bg_extra_tiles)
extern const uint8_t saw_anim_tiles[];   // saw_anim_data.c: SAW_ANIM_FRAMES x SAW_ANIM_TILES x 16 bytes
BANKREF_EXTERN(saw_anim)
static uint8_t mt_saws;
static uint8_t mt_big_saws;   // the level has big saws: SAW_CENTER_MT is their centre

// Metatile tables the renderer uses: the ROM tables, or a per-level copy in WRAM when
// the level moves sheet tiles or overrides metatile tiles.
static const uint8_t (*mt_tab)[4] = metatiles;
static const uint8_t (*mt_tab_rev)[4] = metatiles_rev;
static uint8_t mt_ram[2][FAMIDASH_NUM_METATILES][4];
static uint8_t mt_xlat[256];

// ---- Saw animation: the saw tiles are rewritten through 3 frames (rotated anticlockwise).
// CGB: the VBlank handler GDMAs SAW_CHUNK_TILES tiles of the next frame per VBlank (the saw
// tiles are at VRAM bank 1 slots SAW_VRAM_BASE.. in every level). DMG: the same tiles are
// copied from bg_extra_tiles right after VBlank starts, DMG_SAW_TILES_PER_FRAME per frame,
// into the slots this level loaded them to.
#define SAW_STEP_FRAMES        2    // idle frames between finishing one animation frame and starting the next
#define SAW_CHUNK_TILES        13   // CGB tiles per VBlank (SAW_ANIM_TILES / 4)
#define DMG_SAW_TILES_PER_FRAME 5
static uint8_t saw_on;               // this level has saws
static uint8_t saw_reversed;
static uint8_t saw_frame;            // frame being / last uploaded
static uint8_t saw_pos;              // next tile of that frame; == SAW_ANIM_TILES: idle
static uint8_t saw_timer;
static uint8_t saw_issued;           // CGB: chunk handed to the VBlank handler, not yet done
static uint8_t saw_dmg_slot[SAW_ANIM_TILES];   // DMG: VRAM slot of each saw tile (0xFF: not loaded)

static void saw_anim_reset(void) {
    saw_frame = 0;
    saw_pos = SAW_ANIM_TILES;
    saw_timer = 0;
    saw_issued = 0;
    bg_saw_pending = 0;
}

// CGB: call once per frame before waiting for VBlank (like request_bg_parallax)
void saw_anim_request(void) BANKED {
    if (!saw_on || !bg_gdma_isr_on) return;
    if (saw_issued) {
        if (bg_saw_pending) return;
        saw_issued = 0;
        saw_pos += SAW_CHUNK_TILES;
    }
    if (saw_pos >= SAW_ANIM_TILES) {
        if (++saw_timer < SAW_STEP_FRAMES) return;
        saw_timer = 0;
        saw_frame = (uint8_t)((saw_frame + 1) % SAW_ANIM_FRAMES);
        saw_pos = 0;
    }
    bg_saw_bank = BANK(saw_anim);
    bg_saw_src = saw_anim_tiles + ((uint16_t)(saw_frame * SAW_ANIM_TILES + saw_pos) << 4);
    bg_saw_dst = (uint16_t)0x1000 + ((uint16_t)(SAW_VRAM_BASE + saw_pos) << 4);
    bg_saw_blocks = SAW_CHUNK_TILES;
    bg_saw_pending = 1;
    saw_issued = 1;
}

// DMG: call right after VBlank started
void saw_anim_vblank(void) BANKED {
    if (!saw_on || bg_gdma_isr_on) return;
    if (saw_pos >= SAW_ANIM_TILES) {
        if (++saw_timer < SAW_STEP_FRAMES) return;
        saw_timer = 0;
        saw_frame = (uint8_t)((saw_frame + 1) % SAW_ANIM_FRAMES);
        saw_pos = 0;
    }
    const uint8_t *src = bg_extra_tiles + ((uint16_t)(saw_frame_first[saw_frame] + saw_pos) << 5) + (saw_reversed ? 16 : 0);
    for (uint8_t n = DMG_SAW_TILES_PER_FRAME; n && saw_pos < SAW_ANIM_TILES; n--, saw_pos++, src += 32) {
        uint8_t slot = saw_dmg_slot[saw_pos];
        if (slot != 0xFF) set_bkg_data(slot, 1, src);
    }
}

// Called after the base sheet was uploaded (display off). level: game_levels index.
void apply_level_bg_tiles(uint8_t level, uint8_t reversed) BANKED {
    const uint8_t *r;
    const uint8_t *ov;
    uint8_t n, n_moves, n_over, buf[16];
    uint8_t cgb = (_cpu == CGB_TYPE);
    mt_saws = cgb;
    mt_big_saws = 0;
    saw_on = 0;
    saw_anim_reset();
    mt_tab = metatiles;
    mt_tab_rev = metatiles_rev;
    if (level >= BG_LEVEL_COUNT) return;
    r = cgb ? bg_level_cgb[level] : bg_level_dmg[level];
    mt_big_saws = bg_level_big_saws[level];
    saw_on = bg_level_saws[level];
    saw_reversed = reversed;
    for (n = 0; n < SAW_ANIM_TILES; n++) saw_dmg_slot[n] = 0xFF;

    // Extra tiles: (VRAM bank, slot, count, first extra tile); bank bit 7 = never mirrored
    for (n = *r++; n; n--) {
        uint8_t bank = *r++, dst = *r++, count = *r++;
        uint8_t first_tile = *r++;
        const uint8_t *src = bg_extra_tiles + (uint16_t)first_tile * 32u;
        if (!cgb && count == 1 && first_tile >= saw_frame_first[0] && first_tile < saw_frame_first[0] + SAW_ANIM_TILES) {
            saw_dmg_slot[first_tile - saw_frame_first[0]] = dst;
        }
        if (reversed && !(bank & 0x80)) src += 16;
        if (cgb) VBK_REG = bank & 1;
        while (count--) {
            set_bkg_data(dst++, 1, src);
            src += 32;
        }
        if (cgb) VBK_REG = VBK_TILES;
    }
    n_moves = *r;
    ov = r + 1 + (n_moves << 1);
    n_over = *ov++;
    if (!n_moves && !n_over) return;

    // Moved sheet tiles (DMG: out of the coin sprite tiles) -> per-level metatile table
    n = 0;
    do { mt_xlat[n] = n; } while (++n);
    for (n = n_moves, r++; n; n--) {
        uint8_t dst = *r++, src = *r++;
        get_bkg_data(src, 1, buf);
        set_bkg_data(dst, 1, buf);
        mt_xlat[src] = dst;
    }
    {
        const uint8_t *s = &metatiles[0][0];
        uint8_t *d = &mt_ram[0][0][0];
        for (uint16_t j = 0; j < FAMIDASH_NUM_METATILES * 4u; j++) d[j] = mt_xlat[s[j]];
    }
    for (n = n_over; n; n--) {
        uint8_t m = *ov++, q = *ov++;
        mt_ram[0][m][q] = *ov++;
    }
    n = 0;
    do {
        // reversed table = each metatile's tiles swapped left/right (mirrored sheet)
        mt_ram[1][n][0] = mt_ram[0][n][1]; mt_ram[1][n][1] = mt_ram[0][n][0];
        mt_ram[1][n][2] = mt_ram[0][n][3]; mt_ram[1][n][3] = mt_ram[0][n][2];
    } while (++n);
    mt_tab = mt_ram[0];
    mt_tab_rev = mt_ram[1];
}

// Saw metatile: writes its 4 tiles/attributes (bank 1, mirrored when reversed).
// Positions whose Famidash tile is empty keep the normal transparent tile.
static uint8_t *saw_dst;
static uint8_t *saw_dst_attr;
static void put_saw(uint8_t si, uint8_t reversed, uint8_t r0, uint8_t r1, uint8_t tl_x, uint8_t tr_x) {
    const uint8_t *st = saw_mt_tiles[si - 1];
    uint8_t order0 = reversed ? 1 : 0;
    for (uint8_t i = 0; i < 4; i++) {
        uint8_t t = st[(uint8_t)(i ^ order0)];
        if (t == 0xFF) {
            *saw_dst++ = ((i < 2) ? r0 : r1) + ((i & 1) ? tr_x : tl_x);
            *saw_dst_attr++ = 0x0B;
        } else {
            *saw_dst++ = t;
            *saw_dst_attr++ = reversed ? 0x28 : 0x08; // bank 1, palette 0 (+ X flip)
        }
    }
}

#define BKG_MT_H 16

uint8_t vram_row0_is_ground = 1;
static const uint8_t ground_top[8] = { 48, 49, 49, 49, 49, 49, 49, 50 };
static const uint8_t ground_bot[8] = { 51, 52, 52, 52, 52, 52, 52, 53 };

static uint8_t metatile_column_tiles[BKG_MT_H * 4];
static uint8_t metatile_column_attributes[BKG_MT_H * 4];
static uint8_t col_buf[16];

static uint16_t cur_map_col;

// Builds metatile rows [r_start, r_end) of the column in col_buf into
// metatile_column_tiles/attributes.
static void build_mt_rows(uint8_t reversed, uint8_t r_start, uint8_t r_end) {
    uint8_t tl_x = 0;
    uint8_t tr_x = 1;
    if (_cpu == CGB_TYPE) {
        uint8_t vram_slot = (uint8_t)(cur_map_col & 15u);
        if (reversed) vram_slot = (uint8_t)(-(int8_t)vram_slot & 15u);
        tl_x = (uint8_t)((vram_slot & 3u) << 1);
        tr_x = tl_x + 1u;
    }

    const uint8_t *map_ptr = col_buf + r_start;
    const uint8_t (*mt_table)[4] = reversed ? mt_tab_rev : mt_tab;
    uint8_t *dst = metatile_column_tiles + ((uint8_t)r_start << 2);

    if (_cpu == CGB_TYPE) {
        static const uint8_t row_to_ty0[16] = { 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0 };
        uint8_t *dst_attr = metatile_column_attributes + ((uint8_t)r_start << 2);
        for (uint8_t r = r_start; r < r_end; r++) {
            uint8_t metatile_id = *map_ptr++;
            if (r == 0 && vram_row0_is_ground) {
                *dst++ = ground_top[tl_x];
                *dst++ = ground_top[tr_x];
                *dst++ = ground_bot[tl_x];
                *dst++ = ground_bot[tr_x];
                *dst_attr++ = 0x0C; // Bank 1 + Palette 4
                *dst_attr++ = 0x0C;
                *dst_attr++ = 0x0C;
                *dst_attr++ = 0x0C;
                continue;
            }
            uint8_t r0 = row_to_ty0[r];
            uint8_t r1 = r0 + 8u;
            uint8_t si = saw_mt_index[metatile_id];
            if (si && mt_saws && (metatile_id != SAW_CENTER_MT || mt_big_saws)) {
                saw_dst = dst; saw_dst_attr = dst_attr;
                put_saw(si, reversed, r0, r1, tl_x, tr_x);
                dst += 4; dst_attr += 4;
                continue;
            }
            const uint8_t *tiles = mt_table[metatile_id];
            uint8_t palette = famidash_metatile_palettes[metatile_id];
            uint8_t t;
            t = tiles[0];
            if (t == 12) { *dst++ = r0 + tl_x; *dst_attr++ = 0x0B; } else { *dst++ = t; *dst_attr++ = palette; }
            t = tiles[1];
            if (t == 12) { *dst++ = r0 + tr_x; *dst_attr++ = 0x0B; } else { *dst++ = t; *dst_attr++ = palette; }
            t = tiles[2];
            if (t == 12) { *dst++ = r1 + tl_x; *dst_attr++ = 0x0B; } else { *dst++ = t; *dst_attr++ = palette; }
            t = tiles[3];
            if (t == 12) { *dst++ = r1 + tr_x; *dst_attr++ = 0x0B; } else { *dst++ = t; *dst_attr++ = palette; }
        }
    } else {
        for (uint8_t r = r_start; r < r_end; r++) {
            uint8_t metatile_id = *map_ptr++;
            const uint8_t *tiles = mt_table[metatile_id];

            *dst++ = tiles[0];
            *dst++ = tiles[1];
            *dst++ = tiles[2];
            *dst++ = tiles[3];
        }
    }
}

void prepare_mt_column(uint16_t map_col, const uint8_t* map, uint8_t map_bank, uint8_t reversed) BANKED {
    cur_map_col = map_col;
    get_map_column(map_col, map, map_bank, col_buf);
    build_mt_rows(reversed, 0, BKG_MT_H);
}

// Sliced version: step 0..3 builds metatile rows 4*step .. 4*step+3
// (step 0 also fetches the map column). See flush_mt_column_slice().
void prepare_mt_column_slice(uint16_t map_col, const uint8_t* map, uint8_t map_bank, uint8_t reversed, uint8_t step) BANKED {
    if (step == 0) {
        cur_map_col = map_col;
        get_map_column(map_col, map, map_bank, col_buf);
    }
    build_mt_rows(reversed, (uint8_t)(step << 2), (uint8_t)((step << 2) + 4u));
}

static uint8_t row0_tiles_cache[64];
static uint8_t row0_attrs_cache[64];

void flush_mt_column(uint8_t ring_col) BANKED {
    uint8_t bx = ring_col << 1;
    VBK_REG = VBK_TILES;
    set_bkg_tiles(bx, 0, 2, BKG_MT_H << 1, metatile_column_tiles);
    if (_cpu == CGB_TYPE) {
        VBK_REG = VBK_ATTRIBUTES;
        set_bkg_tiles(bx, 0, 2, BKG_MT_H << 1, metatile_column_attributes);
        VBK_REG = VBK_TILES;
    }
}

// Writes tile rows 8*step .. 8*step+7 of the prepared column (see prepare_mt_column_slice).
void flush_mt_column_slice(uint8_t ring_col, uint8_t step) BANKED {
    uint8_t bx = ring_col << 1;
    uint8_t ty = (uint8_t)(step << 3);
    uint8_t off = (uint8_t)(ty << 1);
    VBK_REG = VBK_TILES;
    set_bkg_tiles(bx, ty, 2, 8, metatile_column_tiles + off);
    if (_cpu == CGB_TYPE) {
        VBK_REG = VBK_ATTRIBUTES;
        set_bkg_tiles(bx, ty, 2, 8, metatile_column_attributes + off);
        VBK_REG = VBK_TILES;
    }
}

// Same as flush_mt_column_slice() but the VBlank handler does the VRAM writes.
void request_mt_column_slice(uint8_t ring_col, uint8_t step) BANKED {
    uint8_t off = (uint8_t)(step << 4);
    bg_cj_x = (uint8_t)(ring_col << 1);
    bg_cj_y = (uint8_t)(step << 3);
    bg_cj_tiles = metatile_column_tiles + off;
    bg_cj_attrs = metatile_column_attributes + off;
    bg_cj_pending = 1;
}

void fill_scroll_bg(const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    uint16_t cols = (map_w < 16) ? map_w : 16;
    for (uint16_t c = 0; c < cols; c++) {
        prepare_mt_column(c, map, map_bank, reversed);
        flush_mt_column((uint8_t)(c % 16));
    }
}

void prepare_row0_level_tiles(uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    const uint8_t (*mt_table)[4] = reversed ? mt_tab_rev : mt_tab;
    uint8_t row0_mt_ids[16];
    get_row0_metatiles(loaded_r, map, map_w, map_bank, reversed, row0_mt_ids);

    for (uint8_t s = 0; s < 16; s++) {
        uint8_t slot = s;
        if (reversed) slot = (uint8_t)(-(int8_t)slot & 15u);
        uint8_t tl_x = (uint8_t)((slot & 3u) << 1);
        uint8_t tr_x = tl_x + 1u;
        uint16_t col = loaded_r - ((loaded_r - slot) & 15u);
        if (col < map_w) {
            uint8_t mt_id = row0_mt_ids[s];
            const uint8_t *tiles = mt_table[mt_id];
            uint8_t pal = famidash_metatile_palettes[mt_id];
            for (uint8_t i = 0; i < 4; i++) {
                uint8_t t = tiles[i];
                uint8_t dst_idx = (i < 2 ? 0 : 32) + (s << 1) + (i & 1);
                if (t == 12) {
                    row0_tiles_cache[dst_idx] = (i < 2 ? 0 : 8) + ((i & 1) ? tr_x : tl_x);
                    row0_attrs_cache[dst_idx] = 0x0B;
                } else {
                    row0_tiles_cache[dst_idx] = t;
                    row0_attrs_cache[dst_idx] = pal;
                }
            }
        }
    }
}

void flush_vram_row0(uint8_t is_ground) BANKED {
    if (_cpu != CGB_TYPE) return;

    if (is_ground) {
        VBK_REG = 0;
        for (uint8_t k = 0; k < 4; k++) {
            set_bkg_tiles((uint8_t)(k << 3), 0, 8, 1, ground_top);
            set_bkg_tiles((uint8_t)(k << 3), 1, 8, 1, ground_bot);
        }
        VBK_REG = 1;
        fill_bkg_rect(0, 0, 32, 2, 0x0C);
        VBK_REG = 0;
    } else {
        VBK_REG = 0;
        set_bkg_tiles(0, 0, 32, 2, row0_tiles_cache);
        VBK_REG = 1;
        set_bkg_tiles(0, 0, 32, 2, row0_attrs_cache);
        VBK_REG = 0;
    }
}


// Builds the top two rows of ring positions first .. first+3 into the handler's
// request buffer (see flush_row0_slots for the tile selection) and requests the upload.
void request_row0_slots(uint8_t first, uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    const uint8_t (*mt_table)[4] = reversed ? mt_tab_rev : mt_tab;
    for (uint8_t n = 0; n < 4; n++) {
        uint8_t s = first + n;
        uint8_t tiles[4];
        uint8_t attrs[4];
        if (vram_row0_is_ground) {
            uint8_t x0 = (uint8_t)((s << 1) & 7u);
            uint8_t x1 = (uint8_t)(((s << 1) + 1u) & 7u);
            tiles[0] = ground_top[x0]; tiles[1] = ground_top[x1];
            tiles[2] = ground_bot[x0]; tiles[3] = ground_bot[x1];
            attrs[0] = attrs[1] = attrs[2] = attrs[3] = 0x0C;
        } else {
            uint8_t slot = s;
            if (reversed) slot = (uint8_t)(-(int8_t)slot & 15u);
            uint8_t tl_x = (uint8_t)((slot & 3u) << 1);
            uint8_t tr_x = tl_x + 1u;
            uint16_t col = loaded_r - ((loaded_r - slot) & 15u);
            uint8_t mt_id = 0;
            if (col < map_w) mt_id = get_map_tile0(col, map, map_bank);
            const uint8_t *mt = mt_table[mt_id];
            uint8_t pal = famidash_metatile_palettes[mt_id];
            for (uint8_t i = 0; i < 4; i++) {
                uint8_t t = mt[i];
                if (t == 12) {
                    tiles[i] = (i < 2 ? 0 : 8) + ((i & 1) ? tr_x : tl_x);
                    attrs[i] = 0x0B;
                } else {
                    tiles[i] = t;
                    attrs[i] = pal;
                }
            }
            uint8_t si = saw_mt_index[mt_id];
            if (si && mt_saws && (mt_id != SAW_CENTER_MT || mt_big_saws)) {
                saw_dst = tiles; saw_dst_attr = attrs;
                put_saw(si, reversed, 0, 8, tl_x, tr_x);
            }
        }
        uint8_t o = (uint8_t)(n << 1);
        bg_rj_tiles[o] = tiles[0]; bg_rj_tiles[o + 1] = tiles[1];
        bg_rj_tiles[8 + o] = tiles[2]; bg_rj_tiles[9 + o] = tiles[3];
        bg_rj_attrs[o] = attrs[0]; bg_rj_attrs[o + 1] = attrs[1];
        bg_rj_attrs[8 + o] = attrs[2]; bg_rj_attrs[9 + o] = attrs[3];
    }
    bg_rj_x = (uint8_t)(first << 1);
    bg_rj_pending = 1;
}

// Rewrites the two top tile rows (row 0/1) of ring positions first .. first+count-1
// as ground or as level tiles, reading the level map for the CURRENT loaded_r.
// Called a couple of positions per frame after a ground/level switch; because
// it always uses the current state it can never overwrite a freshly streamed
// column with stale data. Same tile selection as prepare_row0_level_tiles().
void flush_row0_slots(uint8_t first, uint8_t count, uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    if (_cpu != CGB_TYPE) return;
    const uint8_t (*mt_table)[4] = reversed ? mt_tab_rev : mt_tab;
    uint8_t tiles[4];
    uint8_t attrs[4];
    uint8_t end = first + count;
    for (uint8_t s = first; s < end; s++) {
        if (vram_row0_is_ground) {
            uint8_t x0 = (uint8_t)((s << 1) & 7u);
            uint8_t x1 = (uint8_t)(((s << 1) + 1u) & 7u);
            tiles[0] = ground_top[x0]; tiles[1] = ground_top[x1];
            tiles[2] = ground_bot[x0]; tiles[3] = ground_bot[x1];
            attrs[0] = attrs[1] = attrs[2] = attrs[3] = 0x0C;
        } else {
            uint8_t slot = s;
            if (reversed) slot = (uint8_t)(-(int8_t)slot & 15u);
            uint8_t tl_x = (uint8_t)((slot & 3u) << 1);
            uint8_t tr_x = tl_x + 1u;
            uint16_t col = loaded_r - ((loaded_r - slot) & 15u);
            uint8_t mt_id = 0;
            if (col < map_w) mt_id = get_map_tile0(col, map, map_bank);
            const uint8_t *mt = mt_table[mt_id];
            uint8_t pal = famidash_metatile_palettes[mt_id];
            for (uint8_t i = 0; i < 4; i++) {
                uint8_t t = mt[i];
                if (t == 12) {
                    tiles[i] = (i < 2 ? 0 : 8) + ((i & 1) ? tr_x : tl_x);
                    attrs[i] = 0x0B;
                } else {
                    tiles[i] = t;
                    attrs[i] = pal;
                }
            }
            uint8_t si = saw_mt_index[mt_id];
            if (si && mt_saws && (mt_id != SAW_CENTER_MT || mt_big_saws)) {
                saw_dst = tiles; saw_dst_attr = attrs;
                put_saw(si, reversed, 0, 8, tl_x, tr_x);
            }
        }
        uint8_t x = (uint8_t)(s << 1);
        VBK_REG = 0;
        set_bkg_tiles(x, 0, 2, 1, tiles);
        set_bkg_tiles(x, 1, 2, 1, tiles + 2);
        VBK_REG = 1;
        set_bkg_tiles(x, 0, 2, 1, attrs);
        set_bkg_tiles(x, 1, 2, 1, attrs + 2);
        VBK_REG = 0;
    }
}
