#pragma bank 14

#include <gb/gb.h>
#include <stdint.h>
#include <string.h>
#include "collision.h"
#include "famidash_metatiles.h"
#include "bg_parallax.h"
#include <gbdk/incbin.h>

// Famidash spike set B art for the background spikes (Xstep). Metatile 12
// (BOTTOM_BACKGROUND_SPIKES) and 13 (TOP_BACKGROUND_SPIKES) have the transparent tile 12
// where set B has real art, so those two spots use the otherwise unused tiles 0 and 1.
INCBIN(xstep_bgspikes_b, "levels/chr_data/famidash/xstep_bgspikes_b_tiles.bin")
INCBIN_EXTERN(xstep_bgspikes_b)
#define MT_BOTTOM_BG_SPIKES 12
#define MT_TOP_BG_SPIKES    13
#define TILE_BS_TL 0
#define TILE_TOP_BL 1

uint8_t mt_spike_b;

// Sawblades (Famidash SawbladesA, all levels) in CGB VRAM bank 1, and the block set B
// tiles for Clutterfunk. Generated by tools/make_level_tile_patches.py.
#include "tile_patch_tables.h"
INCBIN(saw_tiles, "levels/chr_data/famidash/saw_tiles.bin")
INCBIN_EXTERN(saw_tiles)
INCBIN(blocks_b_patch, "levels/chr_data/famidash/blocks_b_patch.bin")
INCBIN_EXTERN(blocks_b_patch)
static uint8_t mt_saws;

// Called after the level tileset was uploaded (display off).
// flags: LEVEL_TILES_SPIKES_B / LEVEL_TILES_BLOCKS_B (Famidash tile sets of the level).
void apply_level_tile_patch(uint8_t flags, uint8_t reversed) BANKED {
    mt_saws = (_cpu == CGB_TYPE);
    mt_spike_b = ((flags & LEVEL_TILES_SPIKES_B) && !reversed && _cpu == CGB_TYPE) ? 1u : 0u;
    if (_cpu != CGB_TYPE) return;
    VBK_REG = VBK_ATTRIBUTES;
    set_bkg_data(SAW_VRAM_BASE, SAW_TILE_COUNT, saw_tiles);
    VBK_REG = VBK_TILES;
    {
        // Famidash's solid "BLACK_*" fill tile (NES $10, sheet tile 26) is colour 2 =
        // black. The sheet stores it as colour 3, which is black on DMG but white on
        // CGB palette 0 - so on CGB rewrite it as colour 2.
        static const uint8_t black_fill[16] = {
            0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF,
            0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF
        };
        set_bkg_data(26, 1, black_fill);
    }
    if (flags & LEVEL_TILES_BLOCKS_B) {
        const uint8_t *src = blocks_b_patch + (reversed ? 16 : 0);
        for (uint8_t i = 0; i < BLOCKS_B_PATCH_COUNT; i++) {
            set_bkg_data(blocks_b_patch_tiles[i], 1, src);
            src += 32;
        }
    }
    if (!mt_spike_b) return;
    set_bkg_data(0, 2, xstep_bgspikes_b);
    set_bkg_data(23, 3, xstep_bgspikes_b + 2 * 16);
    set_bkg_data(37, 3, xstep_bgspikes_b + 5 * 16);
}

// Saw metatile: writes its 4 tiles/attributes (bank 1, mirrored when reversed).
// Positions whose Famidash tile is empty keep the normal transparent tile.
static uint8_t *saw_dst;
static uint8_t *saw_dst_attr;
static void put_saw(uint8_t si, uint8_t reversed, uint8_t r0, uint8_t r1, uint8_t tl_x, uint8_t tr_x) {
    const uint8_t *st = saw_mt_tiles[si - 1];
    uint8_t order0 = reversed ? 1 : 0;
    for (uint8_t i = 0; i < 4; i++) {
        uint8_t t = st[(uint8_t)(i ^ order0)];
        if (t == 0xFF) {
            *saw_dst++ = ((i < 2) ? r0 : r1) + ((i & 1) ? tr_x : tl_x);
            *saw_dst_attr++ = 0x0B;
        } else {
            *saw_dst++ = t;
            *saw_dst_attr++ = reversed ? 0x28 : 0x08; // bank 1, palette 0 (+ X flip)
        }
    }
}

#define BKG_MT_H 16

uint8_t vram_row0_is_ground = 1;
static const uint8_t ground_top[8] = { 48, 49, 49, 49, 49, 49, 49, 50 };
static const uint8_t ground_bot[8] = { 51, 52, 52, 52, 52, 52, 52, 53 };

static uint8_t metatile_column_tiles[BKG_MT_H * 4];
static uint8_t metatile_column_attributes[BKG_MT_H * 4];
static uint8_t col_buf[16];

static uint16_t cur_map_col;

// Builds metatile rows [r_start, r_end) of the column in col_buf into
// metatile_column_tiles/attributes.
static void build_mt_rows(uint8_t reversed, uint8_t r_start, uint8_t r_end) {
    uint8_t tl_x = 0;
    uint8_t tr_x = 1;
    if (_cpu == CGB_TYPE) {
        uint8_t vram_slot = (uint8_t)(cur_map_col & 15u);
        if (reversed) vram_slot = (uint8_t)(-(int8_t)vram_slot & 15u);
        tl_x = (uint8_t)((vram_slot & 3u) << 1);
        tr_x = tl_x + 1u;
    }

    const uint8_t *map_ptr = col_buf + r_start;
    const uint8_t (*mt_table)[4] = reversed ? metatiles_rev : metatiles;
    uint8_t *dst = metatile_column_tiles + ((uint8_t)r_start << 2);

    if (_cpu == CGB_TYPE) {
        static const uint8_t row_to_ty0[16] = { 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0, 16, 32, 0 };
        uint8_t *dst_attr = metatile_column_attributes + ((uint8_t)r_start << 2);
        for (uint8_t r = r_start; r < r_end; r++) {
            uint8_t metatile_id = *map_ptr++;
            if (r == 0 && vram_row0_is_ground) {
                *dst++ = ground_top[tl_x];
                *dst++ = ground_top[tr_x];
                *dst++ = ground_bot[tl_x];
                *dst++ = ground_bot[tr_x];
                *dst_attr++ = 0x0C; // Bank 1 + Palette 4
                *dst_attr++ = 0x0C;
                *dst_attr++ = 0x0C;
                *dst_attr++ = 0x0C;
                continue;
            }
            uint8_t r0 = row_to_ty0[r];
            uint8_t r1 = r0 + 8u;
            uint8_t si = saw_mt_index[metatile_id];
            if (si && mt_saws) {
                saw_dst = dst; saw_dst_attr = dst_attr;
                put_saw(si, reversed, r0, r1, tl_x, tr_x);
                dst += 4; dst_attr += 4;
                continue;
            }
            const uint8_t *tiles = mt_table[metatile_id];
            uint8_t palette = famidash_metatile_palettes[metatile_id];
            uint8_t t;
            t = tiles[0];
            if (t == 12 && mt_spike_b && metatile_id == MT_BOTTOM_BG_SPIKES) { *dst++ = TILE_BS_TL; *dst_attr++ = palette; }
            else if (t == 12) { *dst++ = r0 + tl_x; *dst_attr++ = 0x0B; } else { *dst++ = t; *dst_attr++ = palette; }
            t = tiles[1];
            if (t == 12) { *dst++ = r0 + tr_x; *dst_attr++ = 0x0B; } else { *dst++ = t; *dst_attr++ = palette; }
            t = tiles[2];
            if (t == 12 && mt_spike_b && metatile_id == MT_TOP_BG_SPIKES) { *dst++ = TILE_TOP_BL; *dst_attr++ = palette; }
            else if (t == 12) { *dst++ = r1 + tl_x; *dst_attr++ = 0x0B; } else { *dst++ = t; *dst_attr++ = palette; }
            t = tiles[3];
            if (t == 12) { *dst++ = r1 + tr_x; *dst_attr++ = 0x0B; } else { *dst++ = t; *dst_attr++ = palette; }
        }
    } else {
        for (uint8_t r = r_start; r < r_end; r++) {
            uint8_t metatile_id = *map_ptr++;
            const uint8_t *tiles = mt_table[metatile_id];

            *dst++ = tiles[0];
            *dst++ = tiles[1];
            *dst++ = tiles[2];
            *dst++ = tiles[3];
        }
    }
}

void prepare_mt_column(uint16_t map_col, const uint8_t* map, uint8_t map_bank, uint8_t reversed) BANKED {
    cur_map_col = map_col;
    get_map_column(map_col, map, map_bank, col_buf);
    build_mt_rows(reversed, 0, BKG_MT_H);
}

// Sliced version: step 0..3 builds metatile rows 4*step .. 4*step+3
// (step 0 also fetches the map column). See flush_mt_column_slice().
void prepare_mt_column_slice(uint16_t map_col, const uint8_t* map, uint8_t map_bank, uint8_t reversed, uint8_t step) BANKED {
    if (step == 0) {
        cur_map_col = map_col;
        get_map_column(map_col, map, map_bank, col_buf);
    }
    build_mt_rows(reversed, (uint8_t)(step << 2), (uint8_t)((step << 2) + 4u));
}

static uint8_t row0_tiles_cache[64];
static uint8_t row0_attrs_cache[64];

void flush_mt_column(uint8_t ring_col) BANKED {
    uint8_t bx = ring_col << 1;
    VBK_REG = VBK_TILES;
    set_bkg_tiles(bx, 0, 2, BKG_MT_H << 1, metatile_column_tiles);
    if (_cpu == CGB_TYPE) {
        VBK_REG = VBK_ATTRIBUTES;
        set_bkg_tiles(bx, 0, 2, BKG_MT_H << 1, metatile_column_attributes);
        VBK_REG = VBK_TILES;
    }
}

// Writes tile rows 8*step .. 8*step+7 of the prepared column (see prepare_mt_column_slice).
void flush_mt_column_slice(uint8_t ring_col, uint8_t step) BANKED {
    uint8_t bx = ring_col << 1;
    uint8_t ty = (uint8_t)(step << 3);
    uint8_t off = (uint8_t)(ty << 1);
    VBK_REG = VBK_TILES;
    set_bkg_tiles(bx, ty, 2, 8, metatile_column_tiles + off);
    if (_cpu == CGB_TYPE) {
        VBK_REG = VBK_ATTRIBUTES;
        set_bkg_tiles(bx, ty, 2, 8, metatile_column_attributes + off);
        VBK_REG = VBK_TILES;
    }
}

// Same as flush_mt_column_slice() but the VBlank handler does the VRAM writes.
void request_mt_column_slice(uint8_t ring_col, uint8_t step) BANKED {
    uint8_t off = (uint8_t)(step << 4);
    bg_cj_x = (uint8_t)(ring_col << 1);
    bg_cj_y = (uint8_t)(step << 3);
    bg_cj_tiles = metatile_column_tiles + off;
    bg_cj_attrs = metatile_column_attributes + off;
    bg_cj_pending = 1;
}

void fill_scroll_bg(const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    uint16_t cols = (map_w < 16) ? map_w : 16;
    for (uint16_t c = 0; c < cols; c++) {
        prepare_mt_column(c, map, map_bank, reversed);
        flush_mt_column((uint8_t)(c % 16));
    }
}

void prepare_row0_level_tiles(uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    const uint8_t (*mt_table)[4] = reversed ? metatiles_rev : metatiles;
    uint8_t row0_mt_ids[16];
    get_row0_metatiles(loaded_r, map, map_w, map_bank, reversed, row0_mt_ids);

    for (uint8_t s = 0; s < 16; s++) {
        uint8_t slot = s;
        if (reversed) slot = (uint8_t)(-(int8_t)slot & 15u);
        uint8_t tl_x = (uint8_t)((slot & 3u) << 1);
        uint8_t tr_x = tl_x + 1u;
        uint16_t col = loaded_r - ((loaded_r - slot) & 15u);
        if (col < map_w) {
            uint8_t mt_id = row0_mt_ids[s];
            const uint8_t *tiles = mt_table[mt_id];
            uint8_t pal = famidash_metatile_palettes[mt_id];
            for (uint8_t i = 0; i < 4; i++) {
                uint8_t t = tiles[i];
                uint8_t dst_idx = (i < 2 ? 0 : 32) + (s << 1) + (i & 1);
                if (t == 12) {
                    row0_tiles_cache[dst_idx] = (i < 2 ? 0 : 8) + ((i & 1) ? tr_x : tl_x);
                    row0_attrs_cache[dst_idx] = 0x0B;
                } else {
                    row0_tiles_cache[dst_idx] = t;
                    row0_attrs_cache[dst_idx] = pal;
                }
            }
        }
    }
}

void flush_vram_row0(uint8_t is_ground) BANKED {
    if (_cpu != CGB_TYPE) return;

    if (is_ground) {
        VBK_REG = 0;
        for (uint8_t k = 0; k < 4; k++) {
            set_bkg_tiles((uint8_t)(k << 3), 0, 8, 1, ground_top);
            set_bkg_tiles((uint8_t)(k << 3), 1, 8, 1, ground_bot);
        }
        VBK_REG = 1;
        fill_bkg_rect(0, 0, 32, 2, 0x0C);
        VBK_REG = 0;
    } else {
        VBK_REG = 0;
        set_bkg_tiles(0, 0, 32, 2, row0_tiles_cache);
        VBK_REG = 1;
        set_bkg_tiles(0, 0, 32, 2, row0_attrs_cache);
        VBK_REG = 0;
    }
}


// Builds the top two rows of ring positions first .. first+3 into the handler's
// request buffer (see flush_row0_slots for the tile selection) and requests the upload.
void request_row0_slots(uint8_t first, uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    const uint8_t (*mt_table)[4] = reversed ? metatiles_rev : metatiles;
    for (uint8_t n = 0; n < 4; n++) {
        uint8_t s = first + n;
        uint8_t tiles[4];
        uint8_t attrs[4];
        if (vram_row0_is_ground) {
            uint8_t x0 = (uint8_t)((s << 1) & 7u);
            uint8_t x1 = (uint8_t)(((s << 1) + 1u) & 7u);
            tiles[0] = ground_top[x0]; tiles[1] = ground_top[x1];
            tiles[2] = ground_bot[x0]; tiles[3] = ground_bot[x1];
            attrs[0] = attrs[1] = attrs[2] = attrs[3] = 0x0C;
        } else {
            uint8_t slot = s;
            if (reversed) slot = (uint8_t)(-(int8_t)slot & 15u);
            uint8_t tl_x = (uint8_t)((slot & 3u) << 1);
            uint8_t tr_x = tl_x + 1u;
            uint16_t col = loaded_r - ((loaded_r - slot) & 15u);
            uint8_t mt_id = 0;
            if (col < map_w) mt_id = get_map_tile0(col, map, map_bank);
            const uint8_t *mt = mt_table[mt_id];
            uint8_t pal = famidash_metatile_palettes[mt_id];
            for (uint8_t i = 0; i < 4; i++) {
                uint8_t t = mt[i];
                if (t == 12 && mt_spike_b && ((i == 0 && mt_id == MT_BOTTOM_BG_SPIKES) || (i == 2 && mt_id == MT_TOP_BG_SPIKES))) {
                    tiles[i] = (i == 0) ? TILE_BS_TL : TILE_TOP_BL;
                    attrs[i] = pal;
                } else if (t == 12) {
                    tiles[i] = (i < 2 ? 0 : 8) + ((i & 1) ? tr_x : tl_x);
                    attrs[i] = 0x0B;
                } else {
                    tiles[i] = t;
                    attrs[i] = pal;
                }
            }
            uint8_t si = saw_mt_index[mt_id];
            if (si && mt_saws) {
                saw_dst = tiles; saw_dst_attr = attrs;
                put_saw(si, reversed, 0, 8, tl_x, tr_x);
            }
        }
        uint8_t o = (uint8_t)(n << 1);
        bg_rj_tiles[o] = tiles[0]; bg_rj_tiles[o + 1] = tiles[1];
        bg_rj_tiles[8 + o] = tiles[2]; bg_rj_tiles[9 + o] = tiles[3];
        bg_rj_attrs[o] = attrs[0]; bg_rj_attrs[o + 1] = attrs[1];
        bg_rj_attrs[8 + o] = attrs[2]; bg_rj_attrs[9 + o] = attrs[3];
    }
    bg_rj_x = (uint8_t)(first << 1);
    bg_rj_pending = 1;
}

// Rewrites the two top tile rows (row 0/1) of ring positions first .. first+count-1
// as ground or as level tiles, reading the level map for the CURRENT loaded_r.
// Called a couple of positions per frame after a ground/level switch; because
// it always uses the current state it can never overwrite a freshly streamed
// column with stale data. Same tile selection as prepare_row0_level_tiles().
void flush_row0_slots(uint8_t first, uint8_t count, uint16_t loaded_r, const uint8_t* map, uint16_t map_w, uint8_t map_bank, uint8_t reversed) BANKED {
    if (_cpu != CGB_TYPE) return;
    const uint8_t (*mt_table)[4] = reversed ? metatiles_rev : metatiles;
    uint8_t tiles[4];
    uint8_t attrs[4];
    uint8_t end = first + count;
    for (uint8_t s = first; s < end; s++) {
        if (vram_row0_is_ground) {
            uint8_t x0 = (uint8_t)((s << 1) & 7u);
            uint8_t x1 = (uint8_t)(((s << 1) + 1u) & 7u);
            tiles[0] = ground_top[x0]; tiles[1] = ground_top[x1];
            tiles[2] = ground_bot[x0]; tiles[3] = ground_bot[x1];
            attrs[0] = attrs[1] = attrs[2] = attrs[3] = 0x0C;
        } else {
            uint8_t slot = s;
            if (reversed) slot = (uint8_t)(-(int8_t)slot & 15u);
            uint8_t tl_x = (uint8_t)((slot & 3u) << 1);
            uint8_t tr_x = tl_x + 1u;
            uint16_t col = loaded_r - ((loaded_r - slot) & 15u);
            uint8_t mt_id = 0;
            if (col < map_w) mt_id = get_map_tile0(col, map, map_bank);
            const uint8_t *mt = mt_table[mt_id];
            uint8_t pal = famidash_metatile_palettes[mt_id];
            for (uint8_t i = 0; i < 4; i++) {
                uint8_t t = mt[i];
                if (t == 12 && mt_spike_b && ((i == 0 && mt_id == MT_BOTTOM_BG_SPIKES) || (i == 2 && mt_id == MT_TOP_BG_SPIKES))) {
                    tiles[i] = (i == 0) ? TILE_BS_TL : TILE_TOP_BL;
                    attrs[i] = pal;
                } else if (t == 12) {
                    tiles[i] = (i < 2 ? 0 : 8) + ((i & 1) ? tr_x : tl_x);
                    attrs[i] = 0x0B;
                } else {
                    tiles[i] = t;
                    attrs[i] = pal;
                }
            }
            uint8_t si = saw_mt_index[mt_id];
            if (si && mt_saws) {
                saw_dst = tiles; saw_dst_attr = attrs;
                put_saw(si, reversed, 0, 8, tl_x, tr_x);
            }
        }
        uint8_t x = (uint8_t)(s << 1);
        VBK_REG = 0;
        set_bkg_tiles(x, 0, 2, 1, tiles);
        set_bkg_tiles(x, 1, 2, 1, tiles + 2);
        VBK_REG = 1;
        set_bkg_tiles(x, 0, 2, 1, attrs);
        set_bkg_tiles(x, 1, 2, 1, attrs + 2);
        VBK_REG = 0;
    }
}
