#pragma bank 47

#include <stdint.h>
#include <gbdk/incbin.h>
#include <gb/gb.h>

// Saw animation frames for the CGB VBlank handler (see mt_renderer.c). The handler copies them with
// GDMA, which needs 16 byte aligned data: this is the only thing in its ROM bank, so it starts at
// the bank's first byte.
BANKREF(saw_anim)

INCBIN(saw_anim_tiles, "levels/chr_data/saw_anim_tiles.bin")   // generated by tools/build_bg_tiles.py
