/* Generated by tools/make_level_tile_patches.py - do not edit */
#ifndef TILE_PATCH_TABLES_H
#define TILE_PATCH_TABLES_H

#define SAW_VRAM_BASE 64
#define SAW_TILE_COUNT 48
#define SAW_MT_COUNT 15

// Saw metatiles: metatile id and its 4 tiles in CGB VRAM bank 1 (0xFF = keep the sheet tile)
// saw_mt_index[metatile] = row in saw_mt_tiles + 1, 0 = not a saw
static const uint8_t saw_mt_index[256] = {
    0, 0, 0, 0, 1, 0, 0, 0, 2, 3, 4, 5, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 6, 7, 8, 9, 0, 10, 11, 12, 13, 14, 0, 15,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
static const uint8_t saw_mt_tiles[SAW_MT_COUNT][4] = {
    { 0x5A, 0x5F, 0xFF, 0xFF }, /* SMALL_SAW_BOTTOM_HALF */
    { 0x60, 0x61, 0x64, 0x65 }, /* MED_SAW_TOP_LEFT */
    { 0x62, 0x63, 0x66, 0x67 }, /* MED_SAW_TOP_RIGHT */
    { 0x68, 0x69, 0x6C, 0x6D }, /* MED_SAW_BOTTOM_LEFT */
    { 0x6A, 0x6B, 0x6E, 0x6F }, /* MED_SAW_BOTTOM_RIGHT */
    { 0xFF, 0x41, 0x50, 0x51 }, /* BIG_SAW_TOP_LEFT */
    { 0x42, 0x43, 0x52, 0x53 }, /* BIG_SAW_TOP_MIDDLE */
    { 0x44, 0xFF, 0x54, 0x55 }, /* BIG_SAW_TOP_RIGHT */
    { 0x46, 0x47, 0x56, 0x57 }, /* BIG_SAW_MIDDLE_LEFT */
    { 0x48, 0x49, 0x58, 0x59 }, /* BIG_SAW_MIDDLE_RIGHT */
    { 0x4A, 0x4B, 0xFF, 0x5B }, /* BIG_SAW_BOTTOM_LEFT */
    { 0x4C, 0x4D, 0x5C, 0x5D }, /* BIG_SAW_BOTTOM_MIDDLE */
    { 0x4E, 0x4F, 0x5E, 0xFF }, /* BIG_SAW_BOTTOM_RIGHT */
    { 0x40, 0x45, 0x5A, 0x5F }, /* SMALL_SAW */
    { 0xFF, 0xFF, 0x40, 0x45 }, /* SMALL_SAW_TOP_HALF */
};

#define BLOCKS_B_PATCH_COUNT 20
// Sheet tiles replaced by Famidash block set B art (Clutterfunk)
static const uint8_t blocks_b_patch_tiles[BLOCKS_B_PATCH_COUNT] = { 82, 83, 84, 85, 86, 87, 98, 99, 100, 101, 102, 103, 110, 111, 112, 113, 122, 123, 124, 125 };

#endif
