#pragma bank 20
#include <gb/gb.h>
#include <gbdk/incbin.h>

BANKREF(chr_gb)

// Base level tile sheet (VRAM tiles 0..BG_BASE_TILE_COUNT-1) and its mirrored copy for
// mirror mode, generated by tools/build_bg_tiles.py from levels/chr_data/bg_tiles.png.
// Same data on DMG and CGB (CGB colours come from the per-metatile palettes).
INCBIN(chr_gb_tiles, "levels/chr_data/bg_base_tiles.bin")
INCBIN(chr_gb_tiles_rev, "levels/chr_data/bg_base_tiles_flipped.bin")
