#!/usr/bin/env python3
"""Convert a Furnace VGM export (SN76489 / Game Gear) into a per-frame register stream.

Usage: gg_music.py [song.vgm]      (default: DryOutGG.vgm in the repo root)

Output: gg/src/gg_music_bank<N>.c (one file per ROM bank, first bank = FIRST_BANK),
        gg/src/gg_music_index.c and gg/src/gg_music.h.

Stream format (one chunk per video frame, played from the vblank interrupt):
    header byte h:
        0x7E        end of song
        0x7F        continue in the next bank
        otherwise   n = h & 0x7F PSG bytes follow; if bit 7 of h is set, one Game Gear
                    stereo (port 0x06) byte comes first
    PSG bytes are raw SN76489 writes (latch/data), written to port 0x7F.

Only register changes are stored. Writes to the noise register are always kept because
writing it restarts the noise generator (drum hits).
"""
import os
import struct
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'gg', 'src')
FIRST_BANK = 4
BANK_SIZE = 16384
FRAME_RATE = 3579545.0 / (228 * 262)   # Game Gear / SMS NTSC vblank rate (~59.92 Hz)
VGM_RATE = 44100.0


def parse_vgm(path):
    d = open(path, 'rb').read()
    assert d[:4] == b'Vgm ', 'not a VGM file (gzip-compressed .vgz is not supported)'
    p = 0x34 + struct.unpack_from('<I', d, 0x34)[0]
    t = 0
    events = []          # (sample time, 'psg'|'pan', byte)
    while p < len(d):
        c = d[p]
        if c == 0x50:
            events.append((t, 'psg', d[p + 1])); p += 2
        elif c == 0x4F:
            events.append((t, 'pan', d[p + 1])); p += 2
        elif c == 0x61:
            t += struct.unpack_from('<H', d, p + 1)[0]; p += 3
        elif c == 0x62:
            t += 735; p += 1
        elif c == 0x63:
            t += 882; p += 1
        elif 0x70 <= c <= 0x7F:
            t += (c & 15) + 1; p += 1
        elif c == 0x66:
            break
        else:
            sys.exit('unsupported VGM command 0x%02x at offset %d' % (c, p))
    return events, t


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'DryOutGG.vgm')
    events, total = parse_vgm(path)
    n_frames = int(total * FRAME_RATE / VGM_RATE) + 1

    by_frame = [[] for _ in range(n_frames)]
    for t, kind, b in events:
        by_frame[int(t * FRAME_RATE / VGM_RATE)].append((kind, b))

    tone = [0, 0, 0]
    vol = [15, 15, 15, 15]
    last_tone = [None, None, None]
    last_vol = [None, None, None, None]
    cur_reg = 0
    cur_is_tone = False

    chunks = []
    for frame in by_frame:
        pan = None
        noise = []
        dirty_tone = set()
        dirty_vol = set()
        for kind, b in frame:
            if kind == 'pan':
                pan = b
            elif b & 0x80:
                reg = (b >> 5) & 3
                if b & 0x10:
                    vol[reg] = b & 15
                    dirty_vol.add(reg)
                    cur_is_tone = False
                elif reg == 3:
                    noise.append(b)
                    cur_is_tone = False
                else:
                    tone[reg] = (tone[reg] & 0x3F0) | (b & 15)
                    dirty_tone.add(reg)
                    cur_reg, cur_is_tone = reg, True
            elif cur_is_tone:
                tone[cur_reg] = ((b & 0x3F) << 4) | (tone[cur_reg] & 15)
                dirty_tone.add(cur_reg)
        out = list(noise)
        for reg in sorted(dirty_vol):
            if vol[reg] != last_vol[reg]:
                out.append(0x80 | (reg << 5) | 0x10 | vol[reg])
                last_vol[reg] = vol[reg]
        for reg in sorted(dirty_tone):
            if tone[reg] != last_tone[reg]:
                out.append(0x80 | (reg << 5) | (tone[reg] & 15))
                out.append((tone[reg] >> 4) & 0x3F)
                last_tone[reg] = tone[reg]
        assert len(out) < 0x7E
        header = len(out) | (0x80 if pan is not None else 0)
        chunks.append(bytes([header]) + (bytes([pan]) if pan is not None else b'') + bytes(out))

    # Pack into banks, leaving room for the 'next bank' marker
    banks = [bytearray()]
    for ch in chunks:
        if len(banks[-1]) + len(ch) > BANK_SIZE - 2:
            banks[-1].append(0x7F)
            banks.append(bytearray())
        banks[-1] += ch
    banks[-1].append(0x7E)

    for old in os.listdir(SRC):
        if old.startswith('gg_music_bank'):
            os.remove(os.path.join(SRC, old))
    for i, data in enumerate(banks):
        bank = FIRST_BANK + i
        with open(os.path.join(SRC, 'gg_music_bank%d.c' % bank), 'w', newline='\n') as f:
            f.write('/* Generated by gg/tools/gg_music.py - do not edit. */\n')
            f.write('#pragma bank %d\n\n#include <stdint.h>\n\n' % bank)
            f.write('const uint8_t gg_music_bank%d[%d] = {\n' % (bank, len(data)))
            for j in range(0, len(data), 24):
                f.write('    ' + ', '.join('0x%02x' % v for v in data[j:j + 24]) + ',\n')
            f.write('};\n')

    with open(os.path.join(SRC, 'gg_music_index.c'), 'w', newline='\n') as f:
        f.write('/* Generated by gg/tools/gg_music.py - do not edit. */\n#include "gg_music.h"\n\n')
        for i in range(len(banks)):
            f.write('extern const uint8_t gg_music_bank%d[];\n' % (FIRST_BANK + i))
        f.write('\nconst uint8_t * const gg_music_banks[GG_MUSIC_BANKS] = {\n')
        for i in range(len(banks)):
            f.write('    gg_music_bank%d,\n' % (FIRST_BANK + i))
        f.write('};\n')
    with open(os.path.join(SRC, 'gg_music.h'), 'w', newline='\n') as f:
        f.write('/* Generated by gg/tools/gg_music.py - do not edit. */\n')
        f.write('#ifndef GG_MUSIC_H\n#define GG_MUSIC_H\n\n#include <stdint.h>\n\n')
        f.write('#define GG_MUSIC_FIRST_BANK %d\n#define GG_MUSIC_BANKS %d\n\n' % (FIRST_BANK, len(banks)))
        f.write('extern const uint8_t * const gg_music_banks[GG_MUSIC_BANKS];\n\n')
        f.write('void music_start(void);\nvoid music_stop(void);\nvoid music_tick(void);\n\n#endif\n')

    print('frames: %d (%.1fs), stream: %d bytes in %d bank(s)' %
          (n_frames, n_frames / FRAME_RATE, sum(len(b) for b in banks), len(banks)))


if __name__ == '__main__':
    main()
