#ifndef BACKONTRACK_16HIGH_H
#define BACKONTRACK_16HIGH_H

#include <stdint.h>

#define BACKONTRACK_16HIGH_WIDTH 846
#define BACKONTRACK_16HIGH_HEIGHT 16
#define BACKONTRACK_16HIGH_TILE_WIDTH (BACKONTRACK_16HIGH_WIDTH * 2)
#define BACKONTRACK_16HIGH_TILE_HEIGHT (BACKONTRACK_16HIGH_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* BACKONTRACK_16HIGH_H */
