#ifndef BASEAFTERBASE_16HIGH_H
#define BASEAFTERBASE_16HIGH_H

#include <stdint.h>

#define BASEAFTERBASE_16HIGH_WIDTH 869
#define BASEAFTERBASE_16HIGH_HEIGHT 16
#define BASEAFTERBASE_16HIGH_TILE_WIDTH (BASEAFTERBASE_16HIGH_WIDTH * 2)
#define BASEAFTERBASE_16HIGH_TILE_HEIGHT (BASEAFTERBASE_16HIGH_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* BASEAFTERBASE_16HIGH_H */
