#ifndef CANTLETGO_16HIGH_H
#define CANTLETGO_16HIGH_H

#include <stdint.h>

#define CANTLETGO_16HIGH_WIDTH 837
#define CANTLETGO_16HIGH_HEIGHT 16
#define CANTLETGO_16HIGH_TILE_WIDTH (CANTLETGO_16HIGH_WIDTH * 2)
#define CANTLETGO_16HIGH_TILE_HEIGHT (CANTLETGO_16HIGH_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* CANTLETGO_16HIGH_H */
