#ifndef JUMPER_16HIGH_H
#define JUMPER_16HIGH_H

#include <stdint.h>

#define JUMPER_16HIGH_WIDTH 897
#define JUMPER_16HIGH_HEIGHT 16
#define JUMPER_16HIGH_TILE_WIDTH (JUMPER_16HIGH_WIDTH * 2)
#define JUMPER_16HIGH_TILE_HEIGHT (JUMPER_16HIGH_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* JUMPER_16HIGH_H */
