#ifndef STEREOMADNESS_16HIGH_H
#define STEREOMADNESS_16HIGH_H

#include <stdint.h>

#define STEREOMADNESS_16HIGH_WIDTH 894
#define STEREOMADNESS_16HIGH_HEIGHT 16
#define STEREOMADNESS_16HIGH_TILE_WIDTH (STEREOMADNESS_16HIGH_WIDTH * 2)
#define STEREOMADNESS_16HIGH_TILE_HEIGHT (STEREOMADNESS_16HIGH_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* STEREOMADNESS_16HIGH_H */
