#ifndef TIMEMACHINE_16HIGH_H
#define TIMEMACHINE_16HIGH_H

#include <stdint.h>

#define TIMEMACHINE_16HIGH_WIDTH 997
#define TIMEMACHINE_16HIGH_HEIGHT 16
#define TIMEMACHINE_16HIGH_TILE_WIDTH (TIMEMACHINE_16HIGH_WIDTH * 2)
#define TIMEMACHINE_16HIGH_TILE_HEIGHT (TIMEMACHINE_16HIGH_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* TIMEMACHINE_16HIGH_H */
