// Generated by tools/make_cube_icon_frames.py. Do not edit.
#ifndef CUBE_ICON_FRAMES_H
#define CUBE_ICON_FRAMES_H

#include <gb/gb.h>
#include <stdint.h>

#define CUBE_ICON_FIRST 0
#define CUBE_ICON_FRAMES 24   // 0..172.5 degrees in 7.5 degree steps; 180..352.5 = flipped both ways

BANKREF_EXTERN(cube_icon_frames)
extern const uint8_t cube_icon_frames[];   // per icon, per frame: left 8x16 pair, right pair (64 bytes)

// Address of an icon's frame in cube_icon_frames
#define CUBE_ICON_FRAME(icon, frame)     (cube_icon_frames + ((uint16_t)((icon) - CUBE_ICON_FIRST) * CUBE_ICON_FRAMES + (frame)) * 64u)

#endif
