// Generated by tools/build_icon_select_gfx.py. Do not edit.
#ifndef ICON_CATALOG_H
#define ICON_CATALOG_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gb/cgb.h>

#define NUM_CUBE_ICONS 7
#define NUM_GAMEMODE_TABS 7
#define NUM_PALETTE_COLORS 12
#define PREVIEW_TILE_BASE 0
#define PREVIEW_TILE_COUNT 16

BANKREF_EXTERN(icon_catalog)
// Bank 24 data: read it from bank 24 code, or use icon_color() from other banks
extern const palette_color_t icon_palette_colors[NUM_PALETTE_COLORS];
extern const uint8_t icon_dmg_shades[NUM_PALETTE_COLORS];
extern const uint8_t icon_preview_tiles[NUM_CUBE_ICONS][PREVIEW_TILE_COUNT * 16];

palette_color_t icon_color(uint8_t idx) BANKED;

#endif // ICON_CATALOG_H
