/* Generated by tools/make_level_complete_gfx.py - do not edit */
#ifndef LEVEL_COMPLETE_GFX_H
#define LEVEL_COMPLETE_GFX_H

#include <stdint.h>

#define LEVEL_COMPLETE_TEXT_COLS 16
#define LEVEL_COMPLETE_TEXT_ROWS 4
#define LEVEL_COMPLETE_TEXT_TILES 64

extern const uint8_t level_complete_text_tiles[LEVEL_COMPLETE_TEXT_TILES * 16];
extern const uint8_t level_complete_text_used[LEVEL_COMPLETE_TEXT_TILES];

#endif
