// Generated by tools/make_music_beats.py. Do not edit.
#ifndef MUSIC_BEATS_H
#define MUSIC_BEATS_H

#include <gb/gb.h>
#include <stdint.h>
#include "hUGEDriver.h"

#define MUSIC_HIT_WEAK 1
#define MUSIC_HIT_STRONG 2

extern volatile uint16_t music_ticks;   // hUGE_dosound calls since the song started (main.c)

// The song that init_music_banked just started (no timeline: no hits)
void music_beats_start(const hUGESong_t *song) BANKED;
// Strongest hit the music played since the last call: 0 none, MUSIC_HIT_WEAK, MUSIC_HIT_STRONG
uint8_t music_beats_poll(void) BANKED;

#endif
