// Generated by tools/gen_title_buttons.py: do not edit
#ifndef TITLE_BUTTONS_H
#define TITLE_BUTTONS_H

#include <gb/gb.h>
#include <gb/cgb.h>
#include <stdint.h>

// Big title buttons. CGB: sprite rims (8x8, OAM y/x/tile/palette) + BG core cells (map x/y,
// tile in VRAM bank 1, attribute) of play, icon, wrench.
typedef struct { const uint8_t *spr; uint8_t nspr; const uint8_t *core; uint8_t ncore; } tb_group_t;
#define TB_PLAY 0
#define TB_ICON 1
#define TB_WRENCH 2
#define TB_OBJ_TILE_BASE 32
#define TB_OBJ_TILE_COUNT 20
#define TB_CORE_TILE_BASE 48
#define TB_CORE_TILE_COUNT 16
#define TB_OBJ_PAL_COUNT 6
#define TB_CORE_PAL_COUNT 3
#define TB_CURSOR_Y 43   // screen y
#define TB_PLAY_CURSOR_X 76
#define TB_ICON_CURSOR_X 32
#define TB_WRENCH_CURSOR_X 120

// DMG side buttons: 5 x 4 map cells per side, blended with the sky for each SCX 0..63
#define TB_DMG_COLS 5
#define TB_DMG_ROWS 4
#define TB_DMG_TILES (TB_DMG_COLS * TB_DMG_ROWS)
#define TB_DMG_BUF_TILE 168
#define TB_DMG_SKY_TILE 53

BANKREF_EXTERN(title_buttons)
extern const uint8_t tb_obj_tiles[];
extern const uint8_t tb_core_tiles[];
extern const palette_color_t tb_obj_palettes[];
extern const palette_color_t tb_core_palettes[];
extern const tb_group_t tb_groups[3];
extern const uint8_t tb_dmg_plain[];   // [side][TB_DMG_TILES * 16]
extern const uint8_t tb_dmg_left[2];   // screen x of the art, [side]
extern const uint8_t tb_dmg_row0[2];   // first map row, [side]

BANKREF_EXTERN(tb_dmg_icon_0)
extern const uint8_t tb_dmg_icon_0[];
BANKREF_EXTERN(tb_dmg_icon_1)
extern const uint8_t tb_dmg_icon_1[];
BANKREF_EXTERN(tb_dmg_wrench_0)
extern const uint8_t tb_dmg_wrench_0[];
BANKREF_EXTERN(tb_dmg_wrench_1)
extern const uint8_t tb_dmg_wrench_1[];

#endif
