"""Builds the gameplay sprite tiles from ONE image: levels/chr_data/sprite_tiles.png.

    python tools/build_sprite_tiles.py

The image is laid out like sprite VRAM in 8x16 mode: every cell is one tile pair
(tile 2n on top of tile 2n+1), 16 pairs per 16 px row. The grey level of a pixel is its
Game Boy colour index (white = 0, light grey = 1, dark grey = 2, black = 3).

    pair rows  0-7   VRAM bank 0 sprite tiles 0..255 (DMG and CGB)
    pair rows  8-15  CGB VRAM bank 1 sprite tiles 0..255
    pair rows 16-17  DECO_CLOUD: bank 1 tiles 160..199 in levels with Famidash's
                     cloud decorations (Xstep, Clutterfunk)
    pair row  18     CGB_MIRROR_EXIT: CGB version of bank 0 tiles 224..239 (mirror exit
                     portal drawn with colour 3 instead of 2: both mirror portals share
                     sprite palette 6, palette 7 is the HUD text palette)

Only the ranges in LOADS are loaded; the other slots are empty in the image because
gameplay fills them from the font at runtime ("PAUSED" 76..87, debug HUD and % 90..115)
or they are background tiles (bank 0 128..159; DMG coins use 144..159).

Outputs: levels/chr_data/sprite_tiles.bin, src/sprites/sprite_tile_tables.h
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "levels" / "chr_data" / "sprite_tiles.png"

SECTION_ROW = {"BANK0": 0, "BANK1": 8, "DECO_CLOUD": 16, "CGB_MIRROR_EXIT": 18}
# load conditions (must match src/sprites/famidash_sprite_tiles.c)
ALWAYS, CGB, DMG, CGB_DECO, CGB_DECO_CLOUD = 0, 1, 2, 3, 4
LOADS = [  # condition, VRAM bank, first tile, count, source section, first tile in section
    (ALWAYS, 0, 0, 20, "BANK0", 0),        # player: cube 0..7, ship 8..11, ball 12..19
    (ALWAYS, 0, 20, 16, "BANK0", 20),      # death effect
    (ALWAYS, 0, 36, 40, "BANK0", 36),      # pause menu buttons
    (ALWAYS, 0, 88, 2, "BANK0", 88),       # pause menu cursor
    (ALWAYS, 0, 116, 10, "BANK0", 116),    # mini player (cube 0/22/45 deg, ship, ball)
    (ALWAYS, 0, 126, 2, "BANK0", 126),     # mini / growth portal pair 0
    (ALWAYS, 0, 160, 88, "BANK0", 160),    # Famidash objects: portals, pads, orbs, mirror portals, chain
    (ALWAYS, 0, 248, 8, "BANK0", 248),     # mini / growth portal pairs 1..4
    (CGB, 0, 224, 16, "CGB_MIRROR_EXIT", 0),
    (CGB_DECO, 1, 160, 40, "BANK1", 160),  # level decorations
    (CGB_DECO_CLOUD, 1, 160, 40, "DECO_CLOUD", 0),
    (CGB, 1, 200, 16, "BANK1", 200),       # coins
    (DMG, 0, 144, 16, "BANK1", 200),       # coins (DMG: bank 0 tiles 144..159)
]


def main():
    img = Image.open(PNG).convert("L")
    assert img.size[0] == 128 and img.size[1] % 16 == 0, "sprite_tiles.png: 128 px wide, 16 px rows"
    px = img.load()
    idx = lambda v: min(range(4), key=lambda i: abs(v - (255 - 85 * i)))

    def tile(section, i):
        p = i >> 1
        x0, y0 = (p % 16) * 8, (SECTION_ROW[section] + p // 16) * 16 + (i & 1) * 8
        out = bytearray()
        for r in range(8):
            lo = hi = 0
            for x in range(8):
                v = idx(px[x0 + x, y0 + r])
                lo = (lo << 1) | (v & 1)
                hi = (hi << 1) | (v >> 1)
            out += bytes([lo, hi])
        return bytes(out)

    blob = bytearray()
    rows = []
    for cond, bank, first, count, section, src in LOADS:
        rows.append((cond, bank, first, count, len(blob) // 16))
        for i in range(count):
            blob += tile(section, src + i)
    (ROOT / "levels" / "chr_data" / "sprite_tiles.bin").write_bytes(blob)

    L = ["/* Generated by tools/build_sprite_tiles.py from levels/chr_data/sprite_tiles.png - do not edit */",
         "#ifndef SPRITE_TILE_TABLES_H", "#define SPRITE_TILE_TABLES_H", "",
         "#define SPR_ALWAYS 0", "#define SPR_CGB 1", "#define SPR_DMG 2",
         "#define SPR_CGB_DECO 3", "#define SPR_CGB_DECO_CLOUD 4", "",
         "// condition, VRAM bank, first tile, count, first tile in sprite_tiles.bin (lo, hi)",
         "#define SPRITE_LOAD_COUNT %d" % len(rows),
         "static const uint8_t sprite_loads[SPRITE_LOAD_COUNT][6] = {"]
    for cond, bank, first, count, off in rows:
        L.append("    { %d, %d, %d, %d, %d, %d }," % (cond, bank, first, count, off & 255, off >> 8))
    L += ["};", "", "#endif", ""]
    (ROOT / "src" / "sprites" / "sprite_tile_tables.h").write_text("\n".join(L), newline="\n")
    print("sprite_tiles.png: %d tiles in %d load ranges" % (len(blob) // 16, len(rows)))


if __name__ == "__main__":
    main()
