"""Generates src/famidash_bg_tables.h (sky / ground colour shades per NES colour id).

Colours are Famidash's own: the NES master palette that Famidash is normally run
with (Mesen's default 2C02 palette, e.g. 0x1C = #007C8D, 0x0C = #00404D, 0x2A = #5CE430)
and Famidash's oneShadeDarker() (colBrightness(c, 3)): id-0x10, black below 0x10,
0x30 -> 0x10.

usage: python tools/gen_famidash_bg_tables.py
"""
from pathlib import Path

NES = [
    0x666666, 0x002A88, 0x1412A7, 0x3B00A4, 0x5C007E, 0x6E0040, 0x6C0600, 0x561D00,
    0x333500, 0x0B4800, 0x005200, 0x004F08, 0x00404D, 0x000000, 0x000000, 0x000000,
    0xADADAD, 0x155FD9, 0x4240FF, 0x7527FE, 0xA01ACC, 0xB71E7B, 0xB53120, 0x994E00,
    0x6B6D00, 0x388700, 0x0D9300, 0x008F32, 0x007C8D, 0x000000, 0x000000, 0x000000,
    0xFFFEFF, 0x64B0FF, 0x9290FF, 0xC676FF, 0xF36AFF, 0xFE6ECC, 0xFE8170, 0xEA9E22,
    0xBCBE00, 0x88D800, 0x5CE430, 0x45E082, 0x48CDDE, 0x4F4F4F, 0x000000, 0x000000,
    0xFFFEFF, 0xC0DFFF, 0xD3D2FF, 0xE8C8FF, 0xFBC2FF, 0xFEC4EA, 0xFECCC5, 0xF7D8A5,
    0xE4E594, 0xCFEF96, 0xBDF4AB, 0xB3F3CC, 0xB5EBF2, 0xB8B8B8, 0x000000, 0x000000,
]


def rgb8(i):
    v = NES[i]
    return (v >> 16) & 255, (v >> 8) & 255, v & 255


def to555(c):
    r, g, b = (int(round(x * 31 / 255)) for x in c)
    return r | (g << 5) | (b << 10)


def one_shade_darker(i):
    if i < 0x10:
        return 0x0F
    if i == 0x30:
        return 0x10
    return i - 0x10


def lerp(a, b, t):
    return tuple(a[k] + (b[k] - a[k]) * t for k in range(3))


def scale(c, f):
    return tuple(x * f for x in c)


def sky(i):
    """Shades for one sky colour.

    color   = Famidash's exact colour.
    darker  = block/spike gradient step (palettes 0 and 2). It must stay a *smooth* step
              below `color` even for dark skies, where Famidash's oneShadeDarker is black,
              so it is a fixed fraction of `color`.
    border/body/shadow = parallax box outline / fill / drop shadow, also fractions of
              `color`. For Xstep's sky (0x1C) border is exactly Famidash's darker (#00404D).
    """
    color = rgb8(i)
    return [to555(c) for c in (color, scale(color, 0.75), scale(color, 0.52),
                               scale(color, 0.68), scale(color, 0.40))]


def ground(i):
    color = rgb8(i)
    dark = rgb8(one_shade_darker(i))
    grid_9 = scale(color, 0.16)
    # darker = smooth gradient step for ground blocks; grid_18 = Famidash's exact darker shade
    return [to555(c) for c in (scale(color, 0.75), dark, grid_9)]


def main():
    out = ["/* Auto-generated by tools/gen_famidash_bg_tables.py - do not edit by hand */",
           "#ifndef FAMIDASH_BG_TABLES_H", "#define FAMIDASH_BG_TABLES_H", "",
           "#include <stdint.h>", "#include <gb/cgb.h>", "",
           "typedef struct {", "    palette_color_t color;", "    palette_color_t darker;",
           "    palette_color_t border;", "    palette_color_t body;", "    palette_color_t shadow;",
           "} famidash_sky_shades_t;", "",
           "static const famidash_sky_shades_t famidash_sky_table[64] = {"]
    for i in range(64):
        v = sky(i)
        out.append("    { " + ", ".join("0x%04Xu" % x for x in v) + " }, // 0x%02X" % i)
    out += ["};", "", "typedef struct {", "    palette_color_t darker;", "    palette_color_t grid_18;",
            "    palette_color_t grid_9;", "} famidash_ground_shades_t;", "",
            "static const famidash_ground_shades_t famidash_ground_table[64] = {"]
    for i in range(64):
        v = ground(i)
        out.append("    { " + ", ".join("0x%04Xu" % x for x in v) + " }, // 0x%02X" % i)
    out += ["};", "", "#endif /* FAMIDASH_BG_TABLES_H */", ""]
    path = Path(__file__).resolve().parent.parent / "src" / "famidash_bg_tables.h"
    old = path.read_text(encoding="utf-8")
    print("old file ended with:", repr(old[-60:]))
    path.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print("wrote", path)


if __name__ == "__main__":
    main()
