"""DMG object icons: one sprite per orb and pad instead of the CGB art, and a symbol badge on the portals.

    python tools/make_dmg_object_icons.py

Orbs and pads are 2 sprites each on CGB; DMG draws them as a single 8x16 sprite with a
symbol for its type (cheaper, and readable without colours). Portals keep their art and get
a badge with the mode symbol on their side, since on DMG they only differ by colour. Pixels: '.' = 0
(transparent), '1' / '2' / '3' = light grey / dark grey / black. Orbs and pads only use the
top 8 rows (the bottom tile is empty), badges are 8x16.

Writes src/sprites/dmg_object_icons.h (tile data, included by famidash_sprite_tiles.c) and a
preview, levels/chr_data/dmg_object_icons.png.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent

E8 = ["........"] * 8

ORB_YELLOW = [   # jump orb: solid ball
    "..3333..",
    ".311113.",
    "31111113",
    "31111113",
    "31111113",
    "31111113",
    ".311113.",
    "..3333..",
]
ORB_BLUE = [     # gravity orb: dark ball, light up/down arrow
    "..3333..",
    ".321123.",
    "32111123",
    "32211223",
    "32211223",
    "32111123",
    ".321123.",
    "..3333..",
]
ORB_PINK = [     # small jump orb: hollow ring
    "........",
    "..3333..",
    ".31..13.",
    ".3....3.",
    ".3....3.",
    ".31..13.",
    "..3333..",
    "........",
]
PAD_YELLOW = [   # jump pad: solid light triangle (narrow top, wide bottom) on a base
    "...33...",
    "..3113..",
    "..3113..",
    ".311113.",
    ".311113.",
    "31111113",
    "33333333",
    "........",
]
PAD_BLUE = [     # gravity pad: dark hourglass (wide top and bottom): a different
    "33333333",  # silhouette from the yellow triangle even with LCD ghosting
    ".322223.",
    "..3223..",
    "...33...",
    "..3223..",
    ".322223.",
    "33333333",
    "........",
]
PAD_PINK = [     # small jump pad: low dome on a base
    "........",
    "........",
    "........",
    "..3333..",
    ".311113.",
    "31111113",
    "33333333",
    "........",
]


def badge(symbol):
    """Portal badge: the small half disc on the side of the original portal art (like the
    mode icons on Geometry Dash portals), light with a 4x6 black symbol in rows 5..10."""
    assert len(symbol) == 6
    rows = ["33333...", "311113..", "3111113.", "31111113", "31111113"]
    rows += ["31" + s.replace(".", "1") + "13" for s in symbol]
    rows += ["31111113", "31111113", "3111113.", "311113..", "33333..."]
    assert len(rows) == 16 and all(len(r) == 8 for r in rows), rows
    return rows


BADGE_CUBE = badge(["3333", "3..3", "3..3", "3..3", "3..3", "3333"])
BADGE_SHIP = badge(["3...", "33..", "3333", "3333", "33..", "3..."])
BADGE_BALL = badge([".33.", "3333", "3333", "3333", "3333", ".33."])
BADGE_GRAVITY = badge([".33.", ".33.", ".33.", "3333", "3333", ".33."])   # down; up = flipped
BADGE_MINI = badge(["....", "....", "3333", "3333", "....", "...."])      # minus
BADGE_GROW = badge(["....", ".33.", "3333", "3333", ".33.", "...."])      # plus

# Tile pair order: must match DMG_ICON_* / DMG_BADGE_* in src/sp_draw.c. The orb and pad
# icons go to sprite tiles 180..191 (the CGB orb/pad art), the badges to 202..207 and
# 240..245 (unused on DMG); the portals keep their own art.
PAIRS = [
    ORB_YELLOW + E8, ORB_BLUE + E8, ORB_PINK + E8,
    PAD_YELLOW + E8, PAD_BLUE + E8, PAD_PINK + E8,
    BADGE_CUBE, BADGE_SHIP, BADGE_BALL, BADGE_GRAVITY, BADGE_MINI, BADGE_GROW,
]


def tile_bytes(rows):
    out = []
    for r in rows:
        assert len(r) == 8, r
        lo = hi = 0
        for x, ch in enumerate(r):
            c = 0 if ch == "." else int(ch)
            lo |= (c & 1) << (7 - x)
            hi |= (c >> 1) << (7 - x)
        out += [lo, hi]
    return out


def main():
    data = []
    for p in PAIRS:
        data += tile_bytes(p[:8]) + tile_bytes(p[8:])
    lines = ["// Generated by tools/make_dmg_object_icons.py - do not edit",
             "#define DMG_OBJECT_ICON_TILES %d" % (len(PAIRS) * 2),
             "static const uint8_t dmg_object_icon_tiles[] = {"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    (ROOT / "src" / "sprites" / "dmg_object_icons.h").write_text("\n".join(lines) + "\n")

    shade = {".": (160, 200, 160), "1": (170, 170, 170), "2": (85, 85, 85), "3": (0, 0, 0)}
    im = Image.new("RGB", (len(PAIRS) * 10, 16), (255, 255, 255))
    for i, p in enumerate(PAIRS):
        for y, r in enumerate(p):
            for x, ch in enumerate(r):
                im.putpixel((i * 10 + x, y), shade[ch])
    im.save(ROOT / "levels" / "chr_data" / "dmg_object_icons.png")


if __name__ == "__main__":
    main()
