"""Builds the "LEVEL COMPLETE!" text tiles for STATE_LEVEL_COMPLETE.

    python tools/make_level_complete_gfx.py

levels/chr_data/lvl_complete.chr is a Game Boy tile dump (2bpp, 16 bytes per tile). Its first 64 tiles
are the text, 16 tiles wide and 4 rows tall, in reading order (tile i = column i % 16, row i // 16):
"LEVEL" on rows 0..1, "COMPLETE!" on rows 2..3. Colour 0 is the background, 1 / 2 the light / dark
green of the letters, 3 their outline.

Output: src/graphics/level_complete_gfx.c (bank 28, next to the settings box graphics)
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHR = ROOT / "levels" / "chr_data" / "lvl_complete.chr"
OUT = ROOT / "src" / "graphics" / "level_complete_gfx.c"
COLS, ROWS = 16, 4


def main():
    data = CHR.read_bytes()[: COLS * ROWS * 16]
    lines = ["/* Generated by tools/make_level_complete_gfx.py from levels/chr_data/lvl_complete.chr - do not edit */",
             "#pragma bank 28", "", '#include "level_complete_gfx.h"', "",
             "const uint8_t level_complete_text_tiles[LEVEL_COMPLETE_TEXT_TILES * 16] = {"]
    for i in range(COLS * ROWS):
        lines.append("    " + ", ".join("0x%02X" % b for b in data[i * 16:(i + 1) * 16]) + ", // tile %d (col %d, row %d)"
                     % (i, i % COLS, i // COLS))
    lines += ["};", "",
              "// 1 = the tile has art (blank tiles are not drawn)",
              "const uint8_t level_complete_text_used[LEVEL_COMPLETE_TEXT_TILES] = {"]
    used = [int(any(data[i * 16:(i + 1) * 16])) for i in range(COLS * ROWS)]
    for r in range(ROWS):
        lines.append("    " + ", ".join(str(u) for u in used[r * COLS:(r + 1) * COLS]) + ",")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines), newline="\n")
    (ROOT / "include" / "level_complete_gfx.h").write_text("\n".join([
        "/* Generated by tools/make_level_complete_gfx.py - do not edit */",
        "#ifndef LEVEL_COMPLETE_GFX_H", "#define LEVEL_COMPLETE_GFX_H", "",
        "#include <stdint.h>", "",
        "#define LEVEL_COMPLETE_TEXT_COLS %d" % COLS,
        "#define LEVEL_COMPLETE_TEXT_ROWS %d" % ROWS,
        "#define LEVEL_COMPLETE_TEXT_TILES %d" % (COLS * ROWS), "",
        "extern const uint8_t level_complete_text_tiles[LEVEL_COMPLETE_TEXT_TILES * 16];",
        "extern const uint8_t level_complete_text_used[LEVEL_COMPLETE_TEXT_TILES];", "",
        "#endif", ""]), newline="\n")
    print("%d text tiles, %d with art" % (COLS * ROWS, sum(used)))


if __name__ == "__main__":
    main()
