"""Generates the CGB Play / Menu / Restart buttons of the pause menu (src/graphics/pause_buttons_cgb.inc).

Like the Geometry Dash buttons: white ring, green body split light (top half) / dark (bottom half),
a coloured icon (yellow play triangle, cyan menu list, cyan restart arrow). Each button is drawn
as columns of two 8x16 sprites; the split of the body is the boundary between the two sprites, so
the top sprite uses a palette with the light green and the bottom one the dark green:
colour 1 = ring, 2 = body, 3 = icon.

    python tools/make_pause_buttons.py [preview.png]
"""
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "graphics" / "pause_buttons_cgb.inc"

RING_W = 1.5


def blank(cols):
    return [[0] * (cols * 8) for _ in range(32)]


def disc(g, cx, cy, r):
    """white ring + body of a circle; the body is colour 2 everywhere (the palette splits it)"""
    for y in range(32):
        for x in range(len(g[0])):
            d = math.hypot(x + 0.5 - cx, y + 0.5 - cy)
            if d <= r:
                g[y][x] = 1 if d >= r - RING_W else 2


def inside(px, py, poly):
    n, c = len(poly), False
    for i in range(n):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % n]
        if (y1 > py) != (y2 > py) and px < (x2 - x1) * (py - y1) / (y2 - y1) + x1:
            c = not c
    return c


def fill_poly(g, poly, colour=3):
    for y in range(32):
        for x in range(len(g[0])):
            if inside(x + 0.5, y + 0.5, poly):
                g[y][x] = colour


def play():
    g = blank(4)
    disc(g, 16, 16, 16.0)
    fill_poly(g, [(11.0, 7.0), (11.0, 25.0), (25.5, 16.0)])
    return g


def menu():
    g = blank(3)
    disc(g, 12, 16, 12.0)
    for i in range(3):
        y = 10 + i * 5
        for dy in range(3):
            for dx in range(3):                   # dot
                g[y + dy][6 + dx] = 3
            for dx in range(8):                   # bar
                g[y + dy][11 + dx] = 3
    return g


def restart():
    g = blank(3)
    disc(g, 12, 16, 12.0)
    cx, cy = 12.0, 16.0
    for y in range(32):
        for x in range(24):
            r = math.hypot(x + 0.5 - cx, y + 0.5 - cy)
            if 3.3 <= r <= 6.9:
                a = math.degrees(math.atan2(y + 0.5 - cy, x + 0.5 - cx))   # 0 = right, 90 = down
                if not (-100 <= a <= -35):                                  # gap at the top right
                    g[y][x] = 3
    # arrow head on the arc's end at the top, pointing clockwise (to the right)
    fill_poly(g, [(10.5, 6.0), (10.5, 15.5), (18.5, 10.75)])
    return g


def tiles(grid, cols):
    out = []
    for c in range(cols):
        for r in range(4):
            for y in range(8):
                lo = hi = 0
                for x in range(8):
                    v = grid[r * 8 + y][c * 8 + x]
                    lo = (lo << 1) | (v & 1)
                    hi = (hi << 1) | (v >> 1)
                out += [lo, hi]
    return out


def fmt(name, data):
    lines = ["const uint8_t %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    return lines


def main():
    p, m, r = play(), menu(), restart()
    lines = ["/* Generated by tools/make_pause_buttons.py - do not edit */", ""]
    lines += ["// CGB pause menu buttons: columns of 2 sprites (4 tiles), top sprite / bottom sprite palettes", ""]
    lines += fmt("pause_play_tiles_cgb", tiles(p, 4)) + [""]
    lines += fmt("pause_menu_tiles_cgb", tiles(m, 3)) + [""]
    lines += fmt("pause_restart_tiles_cgb", tiles(r, 3))
    OUT.write_text("\n".join(lines) + "\n", newline="\n")
    if len(sys.argv) > 1:
        from PIL import Image
        icon = {1: (255, 255, 255)}
        im = Image.new("RGB", (32 * 3 + 12, 32), (40, 50, 90))
        x0 = 0
        for g, w, ic in ((m, 24, (30, 245, 255)), (p, 32, (255, 235, 20)), (r, 24, (30, 245, 255))):
            for y in range(32):
                for x in range(w):
                    v = g[y][x]
                    if v == 0:
                        continue
                    body = (176, 232, 96) if y < 16 else (116, 196, 52)
                    im.putpixel((x0 + x, y), {1: (255, 255, 255), 2: body, 3: ic}[v])
            x0 += w + 6
        im.resize((im.width * 8, im.height * 8), Image.NEAREST).save(sys.argv[1])


if __name__ == "__main__":
    main()
