"""DMG object icons: one 8x16 sprite per orb, pad and portal instead of the CGB art.

    python tools/make_dmg_object_icons.py

The CGB objects are 2..9 sprites each; on DMG that cost too many CPU cycles per frame, so
every object is drawn as a single 8x16 sprite with a symbol for its type. Pixels: '.' = 0
(transparent), '1' / '2' / '3' = light grey / dark grey / black. Orbs and pads only use the
top 8 rows (the bottom tile is empty).

Writes src/sprites/dmg_object_icons.h (tile data, included by famidash_sprite_tiles.c) and a
preview, levels/chr_data/dmg_object_icons.png.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent

E8 = ["........"] * 8

ORB_YELLOW = [   # jump orb: solid ball
    "..3333..",
    ".311113.",
    "31111113",
    "31111113",
    "31111113",
    "31111113",
    ".311113.",
    "..3333..",
]
ORB_BLUE = [     # gravity orb: dark ball, light up/down arrow
    "..3333..",
    ".321123.",
    "32111123",
    "32211223",
    "32211223",
    "32111123",
    ".321123.",
    "..3333..",
]
ORB_PINK = [     # small jump orb: hollow ring
    "........",
    "..3333..",
    ".31..13.",
    ".3....3.",
    ".3....3.",
    ".31..13.",
    "..3333..",
    "........",
]
PAD_YELLOW = [   # jump pad: arrow up on a base
    "...33...",
    "..3113..",
    ".311113.",
    "33311333",
    "..3113..",
    "..3113..",
    "33333333",
    "31111113",
]
PAD_BLUE = [     # gravity pad: diamond on a base
    "...33...",
    "..3223..",
    ".322223.",
    ".322223.",
    "..3223..",
    "...33...",
    "33333333",
    "32222223",
]
PAD_PINK = [     # small jump pad: low arrow on a base
    "........",
    "........",
    "...33...",
    "..3113..",
    ".311113.",
    "33333333",
    "31111113",
    "........",
]


def capsule(symbol):
    """Portal: a tall capsule outline with a 4x6 symbol in the middle (rows 5..10)."""
    rows = ["..3333..", ".311113.", "31....13", "31....13", "31....13"]
    for s in symbol:
        rows.append("31" + s + "13")
    rows += ["31....13", "31....13", "31....13", ".311113.", "..3333.."]
    assert len(rows) == 16, len(rows)
    return rows


PORTAL_CUBE = capsule(["....", "3333", "3113", "3113", "3333", "...."])
PORTAL_SHIP = capsule(["3...", "33..", "3133", "3133", "33..", "3..."])
PORTAL_BALL = capsule(["....", ".33.", "3113", "3113", ".33.", "...."])
PORTAL_GRAVITY = capsule([".33.", ".33.", ".33.", "3333", ".33.", "...."])   # down; up = flipped
PORTAL_MINI = capsule(["....", "....", "3333", "3333", "....", "...."])      # minus
PORTAL_GROW = capsule(["....", ".33.", "3333", "3333", ".33.", "...."])      # plus
PORTAL_MIRROR = capsule(["....", "3..3", "3333", "3333", "3..3", "...."])    # <->

# Tile pair order: must match DMG_ICON_* in src/sp_draw.c
PAIRS = [
    ORB_YELLOW + E8, ORB_BLUE + E8, ORB_PINK + E8,
    PAD_YELLOW + E8, PAD_BLUE + E8, PAD_PINK + E8,
    PORTAL_CUBE, PORTAL_SHIP, PORTAL_BALL, PORTAL_GRAVITY,
    PORTAL_MINI, PORTAL_GROW, PORTAL_MIRROR,
]


def tile_bytes(rows):
    out = []
    for r in rows:
        assert len(r) == 8, r
        lo = hi = 0
        for x, ch in enumerate(r):
            c = 0 if ch == "." else int(ch)
            lo |= (c & 1) << (7 - x)
            hi |= (c >> 1) << (7 - x)
        out += [lo, hi]
    return out


def main():
    data = []
    for p in PAIRS:
        data += tile_bytes(p[:8]) + tile_bytes(p[8:])
    lines = ["// Generated by tools/make_dmg_object_icons.py - do not edit",
             "#define DMG_OBJECT_ICON_TILES %d" % (len(PAIRS) * 2),
             "static const uint8_t dmg_object_icon_tiles[] = {"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    (ROOT / "src" / "sprites" / "dmg_object_icons.h").write_text("\n".join(lines) + "\n")

    shade = {".": (160, 200, 160), "1": (170, 170, 170), "2": (85, 85, 85), "3": (0, 0, 0)}
    im = Image.new("RGB", (len(PAIRS) * 10, 16), (255, 255, 255))
    for i, p in enumerate(PAIRS):
        for y, r in enumerate(p):
            for x, ch in enumerate(r):
                im.putpixel((i * 10 + x, y), shade[ch])
    im.save(ROOT / "levels" / "chr_data" / "dmg_object_icons.png")


if __name__ == "__main__":
    main()
