"""Coin sprite tiles from levels/chr_data/coin.chr.

    python tools/make_coin_tiles.py

coin.chr is Game Boy 2bpp, 16 tiles per 128 px row: six 16x16 spin frames, frame k = tiles
2k, 2k+1 (top) and 16+2k, 17+2k (bottom). Sprites are 8x16, so each frame is two tile pairs
(left, right column); the edge-on frame 3 is only 6 px wide and fits ONE pair (columns 4..11):
11 pairs, 22 tiles.

Where they go (src/sprites/famidash_sprite_tiles.c, drawn by draw_oam_coin in sp_draw.c):
    CGB  VRAM bank 1 sprite tiles 200..221, recoloured: shade 2 -> 1, so with the coin palette
         (1 black, 2 / 3 yellow) the star is yellow and the shading black
    DMG  pairs 0..7 -> tiles 144..159, 8..9 -> 192..195 (pink pad art, drawn as an icon on DMG),
         10 -> 246..247 (chain block art, not drawn on DMG)

Writes src/sprites/coin_tiles.h.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHR = ROOT / "levels" / "chr_data" / "coin.chr"
FRAMES = 6
SINGLE = {3: 4}   # frame: first column of its single 8 px column


def main():
    d = CHR.read_bytes()

    def tile_px(t):
        out = []
        for r in range(8):
            lo, hi = d[t * 16 + 2 * r], d[t * 16 + 2 * r + 1]
            out.append([((lo >> (7 - x)) & 1) | (((hi >> (7 - x)) & 1) << 1) for x in range(8)])
        return out

    def frame(k):
        g = [[0] * 16 for _ in range(16)]
        for t, x0, y0 in ((2 * k, 0, 0), (2 * k + 1, 8, 0), (16 + 2 * k, 0, 8), (17 + 2 * k, 8, 8)):
            p = tile_px(t)
            for r in range(8):
                g[y0 + r][x0:x0 + 8] = p[r]
        return g

    pairs = []       # 8x16 pixel columns
    frames = []      # (left pair, right pair or 0xFF, x offset)
    for k in range(FRAMES):
        g = frame(k)
        col = lambda x0: [row[x0:x0 + 8] for row in g]
        if k in SINGLE:
            x0 = SINGLE[k]
            assert all(v == 0 for row in g for x, v in enumerate(row) if not x0 <= x < x0 + 8), k
            frames.append((len(pairs), 0xFF, x0))
            pairs.append(col(x0))
        else:
            frames.append((len(pairs), len(pairs) + 1, 0))
            pairs += [col(0), col(8)]
    assert len(pairs) == 11

    def tiles(recolour):
        out = []
        for p in pairs:
            for row in p:
                lo = hi = 0
                for v in row:
                    v = recolour.get(v, v)
                    lo = (lo << 1) | (v & 1)
                    hi = (hi << 1) | (v >> 1)
                out += [lo, hi]
        return out

    def arr(name, data):
        L = ["static const uint8_t %s[] = {" % name]
        for i in range(0, len(data), 16):
            L.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
        return L + ["};"]

    L = ["// Generated by tools/make_coin_tiles.py from levels/chr_data/coin.chr - do not edit",
         "#define COIN_PAIRS %d" % len(pairs), "#define COIN_FRAMES %d" % FRAMES]
    L += arr("coin_tiles_dmg", tiles({}))
    L += arr("coin_tiles_cgb", tiles({2: 1}))
    (ROOT / "src" / "sprites" / "coin_tiles.h").write_text("\n".join(L) + "\n", newline="\n")
    print("frames (left pair, right pair, x):", frames)


if __name__ == "__main__":
    main()
