"""Generates the CGB Practice button of the pause menu (src/graphics/practice_button_cgb.inc).

The button is a 24x24 circle drawn as 6 8x16 sprites (palette 4: colour 1 white, 2 light body,
3 dark body) with a hollow diamond; the diamond's inside is a second pair of sprites in the middle
column (palette 3: colour 1 pale green top half, 2 bright green bottom half). Like the Geometry
Dash button: white ring, green body split light / dark, white diamond with a two tone inside.

    python tools/make_practice_button.py [preview.png]
"""
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "graphics" / "practice_button_cgb.inc"
CX = CY = 11.5


def circle(x, y):
    d = math.hypot(x - CX, y - CY)
    if d > 12.0:
        return 0
    if d >= 10.6:
        return 1                              # ring
    return 2 if y < 12 else 3                 # body


def diamond_rim(x, y):
    return abs(x - CX) / 5.4 + abs(y - CY) / 9.0 <= 1.0


def diamond_in(x, y):
    return abs(x - CX) / 3.9 + abs(y - CY) / 7.2 <= 1.0


def body_grid():
    g = [[0] * 24 for _ in range(32)]
    for y in range(24):
        for x in range(24):
            v = circle(x, y)
            if v and diamond_rim(x, y):
                v = 0 if diamond_in(x, y) else 1
            g[y][x] = v
    return g


def inside_grid():
    g = [[0] * 8 for _ in range(32)]
    for y in range(24):
        for x in range(8, 16):
            if diamond_in(x, y):
                g[y][x - 8] = 1 if y < 12 else 2
    return g


def tiles(grid, cols):
    out = []
    for c in range(cols):
        for r in range(4):
            for y in range(8):
                lo = hi = 0
                for x in range(8):
                    v = grid[r * 8 + y][c * 8 + x]
                    lo = (lo << 1) | (v & 1)
                    hi = (hi << 1) | (v >> 1)
                out += [lo, hi]
    return out


def fmt(name, data):
    lines = ["const uint8_t %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    return lines


def main():
    body, inside = body_grid(), inside_grid()
    lines = ["/* Generated by tools/make_practice_button.py - do not edit */", "",
             "// CGB Practice button: 6 sprites (3 columns of 4 tiles), palette 4"]
    lines += fmt("practice_button_tiles_cgb", tiles(body, 3))
    lines += ["", "// the inside of its diamond: 2 sprites (the middle column, 4 tiles), palette 3"]
    lines += fmt("practice_diamond_tiles_cgb", tiles(inside, 1))
    OUT.write_text("\n".join(lines) + "\n", newline="\n")
    if len(sys.argv) > 1:
        from PIL import Image
        pal_a = [None, (255, 255, 255), (176, 232, 96), (116, 196, 52)]
        pal_b = [None, (176, 244, 176), (92, 240, 56)]
        im = Image.new("RGB", (24, 24), (12, 12, 20))
        for y in range(24):
            for x in range(24):
                if body[y][x]:
                    im.putpixel((x, y), pal_a[body[y][x]])
                if 8 <= x < 16 and inside[y][x - 8]:
                    im.putpixel((x, y), pal_b[inside[y][x - 8]])
        im.resize((24 * 16, 24 * 16), Image.NEAREST).save(sys.argv[1])


if __name__ == "__main__":
    main()
