"""Builds the "LEVEL COMPLETE!" and "PRACTICE COMPLETE!" text tiles for STATE_LEVEL_COMPLETE.

    python tools/make_level_complete_gfx.py

levels/chr_data/lvl_complete.chr and levels/chr_data/prac_complete.chr are Game Boy tile dumps (2bpp, 16 bytes per tile).
Output: src/graphics/level_complete_gfx.c and include/level_complete_gfx.h (bank 28)
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LVL_CHR = ROOT / "levels" / "chr_data" / "lvl_complete.chr"
PRAC_CHR = ROOT / "levels" / "chr_data" / "prac_complete.chr"
OUT = ROOT / "src" / "graphics" / "level_complete_gfx.c"
COLS, ROWS = 16, 4


def process_chr(path):
    data = path.read_bytes()[: COLS * ROWS * 16]
    tiles = [data[i * 16:(i + 1) * 16] for i in range(COLS * ROWS)]
    unique, cell = [], []
    for t in tiles:
        if not any(t):
            cell.append(0xFF)
            continue
        if t not in unique:
            unique.append(t)
        cell.append(unique.index(t))
    return unique, cell


def main():
    lvl_unique, lvl_cell = process_chr(LVL_CHR)
    prac_unique, prac_cell = process_chr(PRAC_CHR)

    lines = ["/* Generated by tools/make_level_complete_gfx.py from levels/chr_data/{lvl,prac}_complete.chr - do not edit */",
             "#pragma bank 28", "", '#include "level_complete_gfx.h"', "",
             "// LEVEL COMPLETE!: the distinct tiles of the text (2bpp: colour 1 = outline, 2 = light fill, 3 = shaded fill)",
             "const uint8_t level_complete_text_tiles[LEVEL_COMPLETE_TEXT_UNIQUE * 16] = {"]
    for i, t in enumerate(lvl_unique):
        lines.append("    " + ", ".join("0x%02X" % b for b in t) + ", // tile %d" % i)
    lines += ["};", "",
              "// per cell of the 16x4 text (reading order): index into the tiles above, 0xFF = empty",
              "const uint8_t level_complete_text_map[LEVEL_COMPLETE_TEXT_COLS * LEVEL_COMPLETE_TEXT_ROWS] = {"]
    for r in range(ROWS):
        lines.append("    " + ", ".join("0x%02X" % c for c in lvl_cell[r * COLS:(r + 1) * COLS]) + ",")
    lines += ["};", "",
              "// PRACTICE COMPLETE!: distinct tiles",
              "const uint8_t practice_complete_text_tiles[PRACTICE_COMPLETE_TEXT_UNIQUE * 16] = {"]
    for i, t in enumerate(prac_unique):
        lines.append("    " + ", ".join("0x%02X" % b for b in t) + ", // tile %d" % i)
    lines += ["};", "",
              "// per cell of the 16x4 text for practice complete",
              "const uint8_t practice_complete_text_map[LEVEL_COMPLETE_TEXT_COLS * LEVEL_COMPLETE_TEXT_ROWS] = {"]
    for r in range(ROWS):
        lines.append("    " + ", ".join("0x%02X" % c for c in prac_cell[r * COLS:(r + 1) * COLS]) + ",")
    lines += ["};", ""]

    OUT.write_text("\n".join(lines), newline="\n")

    header = [
        "/* Generated by tools/make_level_complete_gfx.py - do not edit */",
        "#ifndef LEVEL_COMPLETE_GFX_H", "#define LEVEL_COMPLETE_GFX_H", "",
        "#include <stdint.h>", "",
        "#define LEVEL_COMPLETE_TEXT_COLS %d" % COLS,
        "#define LEVEL_COMPLETE_TEXT_ROWS %d" % ROWS,
        "#define LEVEL_COMPLETE_TEXT_UNIQUE %d" % len(lvl_unique),
        "#define PRACTICE_COMPLETE_TEXT_UNIQUE %d" % len(prac_unique),
        "#define PRACTICE_COLS 15",
        "#define PRACTICE_X_SHIFT 1", "",
        "extern const uint8_t level_complete_text_tiles[LEVEL_COMPLETE_TEXT_UNIQUE * 16];",
        "extern const uint8_t level_complete_text_map[LEVEL_COMPLETE_TEXT_COLS * LEVEL_COMPLETE_TEXT_ROWS];",
        "extern const uint8_t practice_complete_text_tiles[PRACTICE_COMPLETE_TEXT_UNIQUE * 16];",
        "extern const uint8_t practice_complete_text_map[LEVEL_COMPLETE_TEXT_COLS * LEVEL_COMPLETE_TEXT_ROWS];", "",
        "#endif", ""
    ]
    (ROOT / "include" / "level_complete_gfx.h").write_text("\n".join(header), newline="\n")
    print("Level complete: %d distinct tiles. Practice complete: %d distinct tiles." % (len(lvl_unique), len(prac_unique)))


if __name__ == "__main__":
    main()
