#pragma bank 11

#include <gb/gb.h>
#include <gb/cgb.h>
#include <gbdk/incbin.h>
#include "famidash_sprites.h"

// All gameplay sprite tiles (player, death effect, pause menu, Famidash objects,
// decorations, coins), generated by tools/build_sprite_tiles.py from
// levels/chr_data/sprite_tiles.png. The font-based sprites ("PAUSED", debug HUD, %)
// are loaded by their own modules.
#include "sprite_tile_tables.h"
INCBIN(sprite_tiles, "levels/chr_data/sprite_tiles.bin")
INCBIN_EXTERN(sprite_tiles)

void load_gameplay_sprite_tiles(uint8_t deco_cloud) BANKED {
    uint8_t cgb = (_cpu == CGB_TYPE);
    for (uint8_t i = 0; i < SPRITE_LOAD_COUNT; i++) {
        const uint8_t *l = sprite_loads[i];
        uint8_t cond = l[0];
        if (cond == SPR_CGB && !cgb) continue;
        if (cond == SPR_DMG && cgb) continue;
        if (cond == SPR_CGB_DECO && (!cgb || deco_cloud)) continue;
        if (cond == SPR_CGB_DECO_CLOUD && (!cgb || !deco_cloud)) continue;
        if (cgb) VBK_REG = l[1];
        set_sprite_data(l[2], l[3], sprite_tiles + ((uint16_t)l[4] | ((uint16_t)l[5] << 8)) * 16u);
    }
    if (cgb) VBK_REG = 0;
}
