/* Generated by tools/build_sprite_tiles.py from levels/chr_data/sprite_tiles.png - do not edit */
#ifndef SPRITE_TILE_TABLES_H
#define SPRITE_TILE_TABLES_H

#define SPR_ALWAYS 0
#define SPR_CGB 1
#define SPR_DMG 2
#define SPR_CGB_DECO 3
#define SPR_CGB_DECO_CLOUD 4

// condition, VRAM bank, first tile, count, first tile in sprite_tiles.bin (lo, hi)
#define SPRITE_LOAD_COUNT 11
static const uint8_t sprite_loads[SPRITE_LOAD_COUNT][6] = {
    { 0, 0, 0, 20, 0, 0 },
    { 0, 0, 20, 16, 20, 0 },
    { 0, 0, 36, 28, 36, 0 },
    { 0, 0, 88, 2, 64, 0 },
    { 0, 0, 116, 10, 66, 0 },
    { 0, 0, 126, 2, 76, 0 },
    { 0, 0, 160, 88, 78, 0 },
    { 0, 0, 248, 8, 166, 0 },
    { 1, 0, 224, 16, 174, 0 },
    { 3, 1, 160, 40, 190, 0 },
    { 4, 1, 160, 40, 230, 0 },
};

#endif
