/* Generated by tools/build_sprite_tiles.py from levels/chr_data/sprite_tiles.png - do not edit */
#ifndef SPRITE_TILE_TABLES_H
#define SPRITE_TILE_TABLES_H

#define SPR_ALWAYS 0
#define SPR_CGB 1
#define SPR_DMG 2
#define SPR_CGB_DECO 3
#define SPR_CGB_DECO_CLOUD 4

// condition, VRAM bank, first tile, count, first tile in sprite_tiles.bin (lo, hi)
#define SPRITE_LOAD_COUNT 13
static const uint8_t sprite_loads[SPRITE_LOAD_COUNT][6] = {
    { 0, 0, 0, 20, 0, 0 },
    { 0, 0, 20, 16, 20, 0 },
    { 0, 0, 36, 40, 36, 0 },
    { 0, 0, 88, 2, 76, 0 },
    { 0, 0, 116, 10, 78, 0 },
    { 0, 0, 126, 2, 88, 0 },
    { 0, 0, 160, 88, 90, 0 },
    { 0, 0, 248, 8, 178, 0 },
    { 1, 0, 224, 16, 186, 0 },
    { 3, 1, 160, 40, 202, 0 },
    { 4, 1, 160, 40, 242, 0 },
    { 1, 1, 200, 16, 26, 1 },
    { 2, 0, 144, 16, 42, 1 },
};

#endif
